### ISSUE TITLE
Lua error 10.01.2018

### ISSUE THREAD

**Issue by Terenfirehawk** [Jaliborc/PetTracker#100]
**Running Software (please complete the following information):**
 - Game patch 8.0.1 (27842)
 - Addon version 8.0.6

On log-in.  I have deleted and reinstalled with the same errors.

**Error Logs**

 3x PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
PetTracker\Features\BattleListener.lua:39: in function `Upgrade'
PetTracker\Features\BattleListener.lua:30: in function `?'
PetTracker\PetTracker-8.0.6.lua:40: in function `ForAllModules'
PetTracker\PetTracker-8.0.6.lua:54: in function `?'
PetTracker\PetTracker-8.0.6.lua:21: in function <PetTracker\PetTracker.lua:21>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by christopheml** [comment]
Try following those steps : 

- Exit World of Warcraft 
- Delete `<wow folder>\WTF\Account\<your account>\SavedVariables\PetTracker.lua` 
- Delete  `<wow folder>\WTF\Account\<your account>\SavedVariables\PetTracker.lua.bak` 

This will reset PetTracker's configuration. I had exactly the same problem as you and this fixed the issue. Hope this helps.
