### ISSUE TITLE
the display of the abilities in battle is missing

### ISSUE THREAD

**Issue by ilreberli** [Jaliborc/PetTracker#101]
Game Patch 8.0.1.27843
PetTracker 8.0.6

The display of the abilities is missing (screenshot).
Error Message while startup:

Date: 2018-10-02 19:04:48
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua line 39:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: ?
   [C]: pairs()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: Upgrade()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:30: ?()
   PetTracker\PetTracker.lua:40: ForAllModules()
   PetTracker\PetTracker.lua:54: ?()
   PetTracker\PetTracker.lua:21:
      PetTracker\PetTracker.lua:21
Locals:

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AccountAchievementFilter, v4.0
  AchievementsReminder, v
  Altoholic, vr190
  ArkInventory, v30814
  ArkInventoryRules, v10200
  ArkInventoryRulesExample, v10000
  ArkInventorySearch, v10200
  Atlas, vv1.44.03
  AtlasBattlegrounds, vv1.44.00
  AtlasBurningCrusade, vv1.44.00
  AtlasCataclysm, vv1.44.00
  AtlasClassicWoW, vv1.44.00
  AtlasClassOrderHalls, vv1.44.00
  AtlasDungeonLocs, vv1.44.00
  AtlasLegion, vv1.44.00
  AtlasMistsofPandaria, vv1.44.00
  AtlasOutdoorRaids, vv1.44.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.00
  AtlasWarlordsofDraenor, vv1.44.00
  AtlasWorldEvents, vv3.24
  AtlasWrathoftheLichKing, vv1.44.00
  AtlasLoot, vv8.08.00
  AtlasLootBattleforAzeroth, vv8.08.00
  AtlasLootBurningCrusade, vv8.08.00
  AtlasLootCataclysm, vv8.08.00
  AtlasLootClassic, vv8.08.00
  AtlasLootLegion, vv8.08.00
  AtlasLootMistsofPandaria, vv8.08.00
  AtlasLootWarlordsofDraenor, vv8.08.00
  AtlasLootWrathoftheLichKing, vv8.08.00
  AtlasMajorCitiesEnhanced, vv1.16
  AtlasQuest, v4.11.00
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  auccheapsearcher, v20180721
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Auctionator, v5.0.5
  Bartender4, v4.8.1
  BattlePetDailyTamer, v3.0.4
  BattlePetBreedID, vr179
  BonusRollPreview, v80000.46-Release
  DailyGlobalCheck, v
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.0.10
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.1
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DugisGuideViewerZ, v8.643
  FishingBuddy, v1.9.19
  Grid, v8.0.1.1
  HandyNotes, vv1.5.3
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.41
  KalsTransmogHeadsUp, v1,0
  LargerMacroIconSelection, vv1.3.2
  LegionWardrobe, v30
  MasterPlanA, vA
  mOnArsWardrobeHelper, v1.18.2
  MoveAnything, v17.0.0
  NugComboBar, v8.0.3
  OPie, vVanilla 7
  Outfitter, v5.20.3
  Overachiever, v1.0.4
  OverachieverCache, v1.0.4
  OverachieverTabs, v1.0.4
  OverachieverTrade, v1.0.4
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerJournal, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  Postal, vv3.6.0
  PremadeGroupsFilter, v1.21
  Quartz, v3.4.0
  RaidAchieveFilter, v2.0.2
  RaidAchievement, v
  RaidAchievementOldModules, v
  Rarity, v1.0 (r680-release)
  RarityOptions, v
  Rematch, v4.8.8
  SavedInstances, v8.0.6
  SellJunk, v3.0.16
  SexyMap, vv8.0.8
  SilverDragon, vv4.0.13
  SilverDragonBattleForAzeroth, vv4.0.13
  SilverDragonBurningCrusade, vv4.0.13
  SilverDragonCataclysm, vv4.0.13
  SilverDragonLegion, vv4.0.13
  SilverDragonMists, vv4.0.13
  SilverDragonVanilla, vv4.0.13
  SilverDragonWarlords, vv4.0.13
  SilverDragonWrath, vv4.0.13
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  SpellFlashCore, v2.1.8
  Stubby, v8.0.6161 (SwimmingSeadragon)
  Titan, v5.14.8.80000
  TitanBag, v5.14.8.80000
  TitanClock, v5.14.8.80000
  TitanGold, v5.14.8.80000
  TitanLocation, v5.14.8.80000
  TitanLootType, v5.14.8.80000
  TitanPerformance, v5.14.8.80000
  TitanRepair, v5.14.8.80000
  TitanVolume, v5.14.8.80000
  TitanXP, v5.14.8.80000
  TransmogAway, v8.0.0
  TransmogOutfits, v1.3.2
  TransmogRoulette, v8.0.0.1
  TransmogSetProgress, v8.0.01
  TransmogWishList, v8.0.02
  WeakAuras, v2.7.10
  WorldQuestTracker, v
  ZPerl, v5.6.1
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v8.0.1.80000 <none>
  (ck=11a3)

![02-10-_2018_18-46-45](https://user-images.githubusercontent.com/37041620/46364494-3efcde00-c676-11e8-885d-4b08ae77df49.jpg)

**Comment by Tecfan** [comment]
I have the exact same issue. 

![bug](https://user-images.githubusercontent.com/956878/46581139-2eac8080-ca33-11e8-8e9a-5574fa8fc57b.png)

**Comment by jkpmurray** [comment]
I'm also experiencing it, even on Trainers who were around long before 8.0.1
![wowscrnshot_111018_132925](https://user-images.githubusercontent.com/44919378/48300371-e5959380-e4ec-11e8-96f3-788137591b05.jpg)
