### ISSUE TITLE
Error message after log in or port with a char

### ISSUE THREAD

**Issue by ilreberli** [Jaliborc/PetTracker#102]
Always the most newest versions from Twitch and Battle.net

Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
Time: Wed Oct  3 19:18:20 2018
Count: 6
Stack: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
...erface\AddOns\PetTracker\Features\BattleListener.lua:39: in function `Upgrade'
...erface\AddOns\PetTracker\Features\BattleListener.lua:30: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:40: in function `ForAllModules'
Interface\AddOns\PetTracker\PetTracker.lua:54: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:21: in function <Interface\AddOns\PetTracker\PetTracker.lua:21>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by mushu999** [comment]
Same.

Date: 2018-10-07 07:05:29
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua line 39:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: pairs()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: Upgrade()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:30: ?()
   PetTracker\PetTracker.lua:40: ForAllModules()
   PetTracker\PetTracker.lua:54: ?()
   PetTracker\PetTracker.lua:21:
      PetTracker\PetTracker.lua:21
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

AddOns:
  KalielsTracker, v3.1.1
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AchievementsReminder, v
  AdvancedInterfaceOptions, v1.2.4
  AllTheThings, v1.7.0
  Armory, vv15.0.3
  ArmoryGuildBank, vv15.0.3
  AskMrRobot, v64
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BartrubySummonPet, v1.30
  BattlePetDailyTamer, v3.0.4
  BattlePetBreedID, vr177
  BattlePetCount, v1.8.16
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BigWigs, vv119
  BPGUF, vr8
  BrokerAudioHardware, v1.04
  BtWQuests, v1.23
  BtWQuestsBattleForAzeroth, v13
  BtWQuestsClassic, v3
  BtWQuestsLegion, v13
  Collectinator, v8.0.1.1
  CTBarMod, v8.0.1.4
  CTBottomBar, v8.0.1.5
  CTBuffMod, v8.0.1.0
  CTCore, v8.0.1.5
  CTExpenseHistory, v8.0.1.0
  CTLibrary, v8.0.1.5
  CTMailMod, v8.0.1.5
  CTMapMod, v8.0.5.0
  CTPartyBuffs, v8.0.1.1
  CTTimer, v8.0.1.0
  CTUnitFrames, v8.0.1.5
  CTViewport, v8.0.1.0
  CurrencySorter, v
  DailyGlobalCheck, v
  DailyGlobalCheckLegionRareMobs, v
  DailyGlobalCheckLegionTreasureChests, v
  DailyGlobalCheckLegionWorldQuests, v
  DailyGlobalCheckPetTamers, v
  DejaCharacterStats, v800r110
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  GTFO, v4.46.9
  HandyNotes, vv1.5.3
  HandyNotesArathi, v0.1.0
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.29
  HandyNotesCamelFigurines, v1.3
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesWarfrontTreasures, v1
  Informant, v8.0.6159 (SwimmingSeadragon)
  LFRAdvanced, v8.0.1.27178
  MapCoords, v0.28
  MasterPlanA, vA
  MoveAnything, v17.0.0
  MuffinFactionizer, v8.0.0.03
  NoItsNot, v8.0.1.2
  NPCScan, v8.0.1.12
  oRA3, vv8.0.6
  Overachiever, v1.0.3
  OverachieverCache, v1.0.3
  Pawn, v2.2.28
  PersonalLootHelper, v2.16
  PetBattleMaster, v8.0.0
  PetBattleTeams, v3.3.10
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerJournal, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  PokemonTrainer, v8.0.7
  Possessions, vr16
  PowerAuras, v4.30.0
  QuestCompletist, v108.17
  RaidAchieveFilter, v2.0.2
  RaidAchievement, v
  RaidAchievementOldModules, v
  Rarity, v1.0 (r679-release)
  RarityOptions, v
  RepCalc, v3.7.6a
  Routes, vv1.6.0
  SimpleObjectiveProgress, vr26
  SPTimers, v3.12.2
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TabardAddict, v2.41
  TidyPlatesThreatPlates, v9.0.17
  TidyPlatesContinued, v6.18.12
  TidyPlatesContinuedAlvara, v5a
  TidyPlatesContinuedBlizzardPlates, v1.5
  TidyPlatesContinuedClassicPlates, v
  TidyPlatesContinuedGraphite, v
  TidyPlatesContinuedGrey, v
  TidyPlatesContinuedNeon, v
  TidyPlatesContinuedQuatre, v
  TidyPlatesContinuedRenaitre, vv7.0.3
  TidyPlatesContinuedRoth, v
  TidyPlatesContinuedSimple, v7.3.0
  TidyPlatesContinuedSlimHorizontal, v2.2
  TidyPlatesContinuedSlimVertical, v2.2
  TidyPlatesContinuedHub, v
  TidyPlatesContinuedWidgets, v
  ToyBoxEnhanced, v2.0
  WeakAuras, v2.7.7
  WorldBossTimers, v0.1
  WQAchievements, vv8.0.1-23release
  ZPerl, v5.6.1
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=f8a)

**Comment by sgtevmckay** [comment]
**Same issue(s) as Above:**

**Copy of Error Bellow:**
Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sat Dec  1 11:57:09 2018
Count: 1
Stack: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574>
[C]: ?
[C]: in function `pairs'
...erface\AddOns\PetTracker\Features\BattleListener.lua:39: in function `Upgrade'
...erface\AddOns\PetTracker\Features\BattleListener.lua:30: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:40: in function `ForAllModules'
Interface\AddOns\PetTracker\PetTracker.lua:54: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:21: in function <Interface\AddOns\PetTracker\PetTracker.lua:21>

Locals: errMsg = "...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)"
errorTime = 1452368206.0284
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:378
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:106
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:355
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:386
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by Jaliborc** [comment]
Fixed
