### ISSUE TITLE
PetTracker is duplicating itself in the Interface Panel

### ISSUE THREAD

**Issue by ilreberli** [Jaliborc/PetTracker#103]
Sorry I do not know the Build, there is nothing to see if I open the configuration of PetTracker, but I always have the most newest versions from battle.net and Twitch. First I get the following error after login or start a pet battle.  Then PetTracker is duplicating its entry in the Interface Panel. I have already seen more than a dozen entries in the Interface Panel.

Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu Oct 18 14:53:24 2018
Count: 3
Stack: ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
[C]: ?
[C]: in function `pairs'
...erface\AddOns\PetTracker\Features\BattleListener.lua:39: in function `Upgrade'
...erface\AddOns\PetTracker\Features\BattleListener.lua:30: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:40: in function `ForAllModules'
Interface\AddOns\PetTracker\PetTracker.lua:54: in function `?'
Interface\AddOns\PetTracker\PetTracker.lua:21: in function <Interface\AddOns\PetTracker\PetTracker.lua:21>

Locals: 

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

![image](https://user-images.githubusercontent.com/37041620/47156271-0b14f000-d2e7-11e8-8ec6-db37afff153a.png)

**Comment by Jaliborc** [comment]
Fixed
