### ISSUE TITLE
Patch 7.3

### ISSUE THREAD

**Issue by TYGERLILY425** [Jaliborc/PetTracker#11]
Please update to work with new patch!!!

**Comment by jessli9** [comment]
please update to work with Patch 7.3 Thank you

**Comment by Phoulmouth** [comment]
Will you be updating this or should we all just give up?  You're missing broken shore trainers still and now the mods just broken.  You have received plenty of reports so how about letting us know what is going on?

**Comment by mushu999** [comment]
I have not yet tried this but it appears that the PetTracker mod has an outdated Sushi library in it. My Sushi files are dated 5/11/17 but the newest Sushi library is dated 9/1/17. I am going to update my library files manually and see if that solves this issue. The URL for new library is: [http://jaliborc.github.io/Sushi-3.0/](http://jaliborc.github.io/Sushi-3.0/)
