### ISSUE TITLE
Option to only show unowned pets on map

### ISSUE THREAD

**Issue by mushu999** [Jaliborc/PetTracker#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jaliborc** [comment]
already a thing

**Comment by mushu999** [comment]
Version 8.1.1

Unable to find a config screen to make addon only display unowned pets on map. There are too many icons and I own all of those pets it shows on the map. Is there a slash command to open the options?
