### ISSUE TITLE
Pettracker and Rarity with ElvUI and AddOnSkins

### ISSUE THREAD

**Issue by Elrulia** [Jaliborc/PetTracker#114]
**Running Software (please complete the following information):**
 - Game Patch: 8.1.0 (29235) (Release x64)
 - Addon versions (Doesn't seem to matter)
       PetTracker: 8.1.1 and also tried with 8.1.0
       Rarity: r683-release, r683-alpha-3, r682-release and r682-release
       Elvui: 10.85 and 10.87
       AddOnSkins: 4.07, 4.08 and 4.08-9-g30a09d3-alpha

**Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Bug or interference with each other is unknown for me. However the issue is really annoying as I really love both of the addons. 

My guess is that something from the addons is interfering with each other so this happens.

To the issue, it's that the Rivals tab from PetTracker does not have the ElvUI theme, and when clicked the tab I was just at in the Collection window also stays with the default wow ui theme. 

Two Pictures to show the issue as I dont really know how to describe it by words.
https://i.imgur.com/lxA7w5a.png - in the mount tab and as can seen on the Rivals tab it's the default UI.
https://i.imgur.com/oyncVNx.png - swapped to the Rivals tab and it's the default ui while the Mount tab also gets the default UI. The tab down there is only change until swapped back to any of the other tabs and happens on any of the tab when clicking to the Rivals tab.

This issue however only appears when I have both PetTracker and Rarity on at the same time and not when Rarity is off. It'll then look like following:

https://i.imgur.com/2Cg4sFP.png - in the mount tab
https://i.imgur.com/YVmnrIU.png - in the rivals tab

This is how it is supposed to look when both Rarity and PetTracker is on.

ElvUI and AddOnSkins is on at all time ofc as that's the core addons for my ui theme. 

**To Reproduce**
1. Install ElvUI, AddOnSkins, PetTracker and Rarity.
2. Make a new character with only those 4 addons on.
3. Login and do the base procedure for ElvUI installation.
3.1 Unsure if it's on by default or not
          go to elvui settings (/ec) -> AddOnSkins -> AddOn Skins and then check PetTracker
4. Go to the Collection window.

**Expected behavior**
The Rivals tab should follow the ElvUI theme with Rarity on too.

**Error Logs**
Haven't seen any errors show up.

**Additional context**
Really dont know if the issue is coming from PetTracker, ElvUI, Rarity or AddOnSkins.
But since the issue is appearing on a PetTracker feature  I contact you first.

Can't tell if this have ever worked as I didn't notice it until recently and I'm pretty sure I reenabled Rarity not to long ago since this was the case I unabled Rarity before that for a long period. My memorie can't recall tomuch so this might not have been the case.

**Comment by Jaliborc** [comment]
Report that at ElvUI, we don't deal with skins.
