### ISSUE TITLE
Patch 8.1.5: Error in RivalJournal

### ISSUE THREAD

**Issue by bdongus** [Jaliborc/PetTracker#116]
**Running Software (please complete the following information):**
 - Game patch 8.1.5
 - Addon version

**Have you read the changelog? (please don't waste our time)**
Mark if read. aye

**Describe the bug**
5x PetTracker\Features\RivalJournal.lua:146: attempt to index field 'selected' (a nil value)
PetTracker\Features\RivalJournal.lua:146: in function `update'
PetTracker\Features\RivalJournal.lua:90: in function <PetTracker\Features\RivalJournal.lua:87>

Locals:
self = PetTrackerRivalJournalList {
 0 = <userdata>
 buttons = <table> {
 }
 ScrollChild = PetTrackerRivalJournalListScrollChild {
 }
 scrollUp = PetTrackerRivalJournalListScrollBarScrollUpButton {
 }
 buttonHeight = 46
 scrollDown = PetTrackerRivalJournalListScrollBarScrollDownButton {
 }
 offset = 0
 scrollBar = PetTrackerRivalJournalListScrollBar {
 }
 update = <function> defined @PetTracker\Features\RivalJournal.lua:126
 scrollChild = PetTrackerRivalJournalListScrollChild {
 }
}
self = PetTrackerRivalJournalList {
 0 = <userdata>

**To Reproduce**
1. Open the Rivals tab.

**Expected behavior**
Show the rivals, their details and the previous teams fighting the.

**Comment by Jaliborc** [comment]
Thanks, fixed
