### ISSUE TITLE
Lua Error & no Rival's in Rival Tab

### ISSUE THREAD

**Issue by rhainstorm** [Jaliborc/PetTracker#117]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178] wow 8.1.5
 - Addon version -> Pet Tracker version 8.1.2

**Have you read the changelog? (please don't waste our time)**
Mark if read. yes

**Describe the bug**
1. lua error's
2. no rival's show up on Rival tab no portrait, no names, no info its all blank. except 1 name always shows Julia Stevens 
   No, hide rival portraits is not enabled

**To Reproduce**
not sure.  they just are not there and errors no matter what. i log on and errors pop. no rival's at all time
4. See error. X

**Expected behavior**
fix for the lua error's and to have my rival tab working. please
**Screenshots**
![WoWScrnShot_031519_220854](https://user-images.githubusercontent.com/38485661/54470568-1a09ac80-4778-11e9-821a-8c82521c9875.jpg)

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.
Message: ...nterface\AddOns\PetTracker\Features\RivalJournal.lua:67: attempt to index field 'Count' (a nil value)
Time: Fri Mar 15 21:50:38 2019
Count: 1
Stack: ...nterface\AddOns\PetTracker\Features\RivalJournal.lua:67: attempt to index field 'Count' (a nil value)
[C]: ?
...nterface\AddOns\PetTracker\Features\RivalJournal.lua:67: in function `Startup'
...nterface\AddOns\PetTracker\Features\RivalJournal.lua:295: in function `OnSelect'
...ns\PetTracker\Libs\SecureTabs-2.0\SecureTabs-2.0.lua:60: in function `Select'
...ns\PetTracker\Libs\SecureTabs-2.0\SecureTabs-2.0.lua:42: in function <...ns\PetTracker\Libs\SecureTabs-2.0\SecureTabs-2.0.lua:42>

Locals: 
Message: Couldn't find inherited node: ItemButtonTemplate
Time: Fri Mar 15 21:50:38 2019
Count: 1
**Additional context**

**Comment by Jaliborc** [comment]
This looks exactly like version 8.1.1. Please make sure you are running 8.1.2 and see if the problem persists with other mods disabled.

**Comment by rhainstorm** [comment]
I stated that this addon is current using version 8.1.2. i use ElvUI  but the addon is current. I will try disableing addons although i do not use many addons.  dbm. petbreedid, dugi, world quest tab, gathermate, auctionator and Vudu. thats it outside elvui.  So I will try and see if its something to do with another addon issue.
