### ISSUE TITLE
7.3 bug

### ISSUE THREAD

**Issue by johnn4321** [Jaliborc/PetTracker#12]
Got the following error with 7.3.

ID: 1
Error occured in: Global
Count: 1
Message: ...\PetTracker\Libs\Sushi-3.0\Classes\DropdownFrame.lua line 124:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...\PetTracker\Libs\Sushi-3.0\Classes\DropdownFrame.lua:124: Toggle()
   PetTracker\Features\WorldMap.lua:238:
      PetTracker\Features\WorldMap.lua:237
Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AlreadyKnown, v1.14
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.19
  Babylonian, v5.1.DEV.332(/embedded)
  BadPet, vv1.0.9
  BartrubySummonPet, v1.26
  BattlePetBreedID, vr154
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BulkMail2Inbox, v7.0.0
  BuyEmAll, v3.4.3
  ClassHallButtonGarrison, v
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  DropTheCheapestThing, vv70100
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  GatherMate2, v1.41
  HandyNotes, vv1.4.15
  HandyNotesDungeonLocations, v1.21
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesSuramarTelemancy, v1
  HandyNotesWorldMapButton, v2.6
  Informant, v7.4.5714 (TasmanianThylacine)
  iSoldMore, v
  kSellGreyNRepair, v1.2
  LibExtraTip, v5.12.DEV.423(/embedded)
  MinersCoffeeAndPick, v1.9
  OPie, vVanilla 1
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerBroker, v
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  PremadeGroupsFilter, v1.14
  Rematch, v4.7.5
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  SushiSort, v7.0.0.0
  TheUndermineJournal, v4.7.20170829
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.12.3.70300
  TitanBag, v5.12.3.70300
  TitanClock, v5.12.3.70300
  TitanCurrenciesMulti, v5.26
  TitanGold, v5.12.3.70300
  TitanLootType, v5.12.3.70300
  TitanPerformance, v5.12.3.70300
  TitanRepair, v5.12.3.70300
  TitanVolume, v5.12.3.70300
  TitanXP, v5.12.3.70300
  TomTom, vv70200-1.0.0
  WorldQuestGroupFinder, v0.27
  WorldQuestsList, v42
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=bf6)

**Comment by mushu999** [comment]
I have not yet tried this but it appears that the PetTracker mod has an outdated Sushi library in it. My Sushi files are dated 5/11/17 but the newest Sushi library is dated 9/1/17. I am going to update my library files manually and see if that solves this issue. The URL for new library is: [http://jaliborc.github.io/Sushi-3.0/](http://jaliborc.github.io/Sushi-3.0/)
