### ISSUE TITLE
Map filter feature is undocumented

### ISSUE THREAD

**Issue by sirzooro** [Jaliborc/PetTracker#122]
**Is your feature request related to a problem? Please describe.**
Addon allows to filter which pets should be displayed on map. However this feature is mostly undocumented. Only some possible choices are given as examples, e.g. "missing".

**Describe the solution you'd like**
Please document all possible filters on addon page, as part of addon description.

**Comment by Jaliborc** [comment]
Sure thing, didn't even realize this was a thing.

**Comment by Jaliborc** [comment]
Done, created a wiki

**Comment by sirzooro** [comment]
Thanks, finally! :)

Please also add information about operator priorities with some examples. I can expect that they are same as in other programming languages, but other users probably will not know this.

BTW, do you support parenthesis in search expressions? They would be helpful for more complex searches. De Morgan's laws of course are an alternative, but again this is not a common knowledge.

**Comment by Jaliborc** [comment]
And/or have priority are are done in a pre-processing step. The rest is done atomically by the filters themselves.

**Comment by Jaliborc** [comment]
No parenthesis are supported I believe. Done this years ago.
