### ISSUE TITLE
PetTracker needs to be updated for 8.2 zones

### ISSUE THREAD

**Issue by dblanch369** [Jaliborc/PetTracker#124]
**Running Software (please complete the following information):**
The latest

**Have you read the changelog? (please don't waste our time)**
Mark if read.

Yes

**Describe the bug**
The add-on does not have pet information or tracking in Najzatar or Mechagon

**To Reproduce**

Open main map while in new 8.2 zones

**Expected behavior**
Expect it to show pet locations on main map like other zones (Missing/All/None)

**Comment by Noobydoobie** [comment]
Having identical issue. I thought there may have been a conflict with some other addons but after disabling everything else it appears that may not bee the case.
I read somewhere that the author hadn't been very well and that an update was coming but that was a while ago.

Just wanted to say I hope you are feeling better and I love your addon regardless. ;)

**Comment by mluks** [comment]
The map ids are incorrect in the Data.lua file.  I had issues with this on an addon I support also and got the wrong ones first time around.  They should be 1462 instead of 1490 for Mechagon and 1355 instead of 1504 for Nazjatar.  For a temporary fix, changing these manually in the Data.lua file seems to work for me

**Comment by Jaliborc** [comment]
> The map ids are incorrect in the Data.lua file. I had issues with this on an addon I support also and got the wrong ones first time around. They should be 1462 instead of 1490 for Mechagon and 1355 instead of 1504 for Nazjatar. For a temporary fix, changing these manually in the Data.lua file seems to work for me

Nice catch!
