### ISSUE TITLE
Bug in filter parsing

### ISSUE THREAD

**Issue by sirzooro** [Jaliborc/PetTracker#128]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.0
 - Server patch: [e.g. Build 8.2.0.31478]

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
For more complex filters result depends on order in which expression parts appears.

**To Reproduce**
Steps to reproduce the behaviour:
"missing | pet battle & !rare" - pets from professions are on map
"pet battle & !rare | missing" - pets from professions disappears
Both filters should display pets which are not collected, or are non-rare pets from battles.

Additionally display order depends on filter too - when icons for two pets overlaps, some of them are on top when 1st expression is used, and other ones when 2nd expression is used. This is a cosmetic issue, and it can be left as-is.

**Expected behaviour**
Both filters should give the same result.

**Comment by sirzooro** [comment]
More examples:
- "missing | pet battle & !rare | pt battle & rare & <23" - has typo "pt battle". This filter removed all pets for map;
- "missing | pet battle & !rare | pet battle & rare & <23" - corrected version. It shows captureable non-rare pet with level below 23, but all non-rare pets capturable pets are gone.

Looks that there is something wrong with logic operators, at least they does not follow priorities usually implemented by programming languages (negation first, then AND, then OR). 

BTW, In other issue here you wrote that that parenthesis are also not supported. This complicated things more, as casual addon users usually do not know De Morgan's laws.

**Comment by Jaliborc** [comment]
The wiki describes the order of operations. It works as described

**Comment by sirzooro** [comment]
I have analyzed my expressions more deeply and come to conclusion that OR operator has higher priority than AND operator. With this assumption expression `pet battle & !rare | missing` will be evaluated as `pet battle & (!rare | missing)` (what can be further simplified to `pet battle & missing`), what explains why profession pets disappears from map. 

Expression `missing | pet battle & !rare | pet battle & rare & <23` is evaluated as `(missing | pet battle) & (!rare | pet battle) & rare & <23`, what always is `false`. BTW, `pet battle & rare & <23` itself works expected.

I also considered possibility that operators with equal priorities (in this case AND and OR) are evaluated from right to left, but this does not match observed results.

One more point: I do not agree with statement "Parenthesis are not supported, as the search system is intended for common users not for experts." added to Wiki page. People learn what parenthesis are and how they work early in their math lessons, so this should be common knowledge. Parenthesis are also recommenced in various books for developers, and as a good practice - especially when operator priority can be misleading to less advanced people.

**Comment by sirzooro** [comment]
Wiki specifies following priorities:
- comparison is the highest;
- negation is next;
- AND and OR are equal and lowest

There is no word about operator associativity, i.e. how you evaluate expression when multiple operators with equal priorities.

Filter `pet battle & !rare | missing` does not include uncollected profession pets, so it must be evaluated as `pet battle & (!rare | missing)`. However I have no idea about evaluation order for filter `missing | pet battle & !rare | pet battle & rare & <23`. I tried to analyze what will happen when it will be evaluated from right to left - it this case at least missing pets should be on map. I also checked possibility that OR may have higher priority than AND, but this also should show some pets on map.

Please tell me how exactly this addon evaluates this last expression. And please reconsider adding support for parenthesis. People learn about them early in school at math lessons, so this is not an advanced feature - it reality they will simplify creation of filters.
