### ISSUE TITLE
Map showing all battles

### ISSUE THREAD

**Issue by Zaphod392** [Jaliborc/PetTracker#138]
Seeing all pet battles, and the search window is missing:

5x PetTracker\Features\MapFilter.lua:56: <unnamed> doesn't have a "OnClick" script
[string "=[C]"]: in function `SetScript'
[string "@PetTracker\Features\MapFilter.lua"]:56: in function `Init'
[string "@PetTracker\Features\MapFilter.lua"]:25: in function <PetTracker\Features\MapFilter.lua:24>
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:231: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:37: in function `SetMapID'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:242: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:240>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3283: in function <FrameXML\UIParent.lua:3273>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:432: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
(*temporary) = <unnamed> {
 InitializeDropDown = <function> defined @Blizzard_WorldMap\Blizzard_WorldMapTemplates.lua:19
 OnLoad = <function> defined @Blizzard_WorldMap\Blizzard_WorldMapTemplates.lua:3
 Refresh = <function> defined @Blizzard_WorldMap\Blizzard_WorldMapTemplates.lua:7
 Left = WorldMapFrameLeft {
 }
 Icon = WorldMapFrameIcon {
 }
 Right = WorldMapFrameRight {
 }
 0 = <userdata>
 relativeFrame = <unnamed> {
 }
 Button = WorldMapFrameButton {
 }
 Text = WorldMapFrameText {
 }
 Middle = WorldMapFrameMiddle {
 }
 noResize = 1
}
(*temporary) = "OnClick"
(*temporary) = <function> defined @PetTracker\Features\MapFilter.lua:56

**Comment by karenlk** [comment]
A quick fix for this one: edit the file <your addon folder>\PetTracker\Features\MapFilter.lua
About line 56 should wrap the overlay statement with the if 
new:
```
if overlay.OnClick ~=nil then
      overlay:SetScript('OnClick', function()
        SushiDropFrame:Toggle('TOPLEFT', overlay, 'BOTTOMLEFT', 0, -15, true, self.ShowTrackingTypes)
      end)
end
```
old:
```
      overlay:SetScript('OnClick', function()
        SushiDropFrame:Toggle('TOPLEFT', overlay, 'BOTTOMLEFT', 0, -15, true, self.ShowTrackingTypes)
      end)
```

**Comment by Zaphod392** [comment]
That seems to fix the missing search bar, and I can type in "missing" to only show the ones I don't have.

It does seem to be layered under some test that makes it hard to see what you type, but it does work otherwise!

![PetTracker All pets error](https://user-images.githubusercontent.com/59921692/72458807-50002e80-3797-11ea-90a8-269a8ddd4147.jpg)

**Comment by Meebsy** [comment]
The Pet tracker overlay seems to be causing issues with World Quest Tracker and tooltips for world quests.
Even the temp fix seems to causing the problem too.

**Comment by craig732** [comment]
Sorry I am a noob... Where can I find the file \PetTracker\Features\MapFilter.lua please?  I "searched" my program file folder and it is not found.

**Comment by zalidthebur** [comment]
Thanks karenlk. That did the trick :-)

**Comment by sauljaffe** [comment]
Those lines you suggest changing don't appear in the version I have that was downloaded/updated on Jan. 17.  Putting those lines in breaks PetTracker further.

**Comment by karenlk** [comment]
> 
> 
> Those lines you suggest changing don't appear in the version I have that was downloaded/updated on Jan. 17. Putting those lines in breaks PetTracker further.

Yes this quick fix was for the previous version. There has since been an update by the author. If the lines are different in the new version, then I wouldn't suggest making those changes.

**Comment by sauljaffe** [comment]
> > Those lines you suggest changing don't appear in the version I have that was downloaded/updated on Jan. 17. Putting those lines in breaks PetTracker further.
> 
> Yes this quick fix was for the previous version. There has since been an update by the author. If the lines are different in the new version, then I wouldn't suggest making those changes.

Well, the update from 5 days ago is still broken.  Badly.  No pets show on the world map.  There's no search box.  And I think there are lots of errors.  Next time I play, I'll try and capture them and post them.  PetTracker is pretty useless in this state.

**Comment by zalidthebur** [comment]
> 
> 
> > > Those lines you suggest changing don't appear in the version I have that was downloaded/updated on Jan. 17. Putting those lines in breaks PetTracker further.
> > 
> > 
> > Yes this quick fix was for the previous version. There has since been an update by the author. If the lines are different in the new version, then I wouldn't suggest making those changes.
> 
> Well, the update from 5 days ago is still broken. Badly. No pets show on the world map. There's no search box. And I think there are lots of errors. Next time I play, I'll try and capture them and post them. PetTracker is pretty useless in this state.

Not sure why yours is so broken. Only thing that seems to not be working is the drop-down on the world map. Typing "missing" into the search works as above.
