### ISSUE TITLE
lua error 

### ISSUE THREAD

**Issue by raymbec32** [Jaliborc/PetTracker#139]
Message: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
Time: Tue Jan 21 23:53:37 2020
Count: 1
Stack: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:197: in function `RestoreFilters'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:376: in function `_LoadPetsFinish'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:309: in function `LoadPets'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:422: in function `?'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>

Locals:

**Comment by sauljaffe** [comment]
I'm not seeing those errors.  All I'm seeing is:

98x PetTracker\Features\MapFilter.lua:1: unexpected symbol near '`'


Locals:

**Comment by sauljaffe** [comment]
There was a '`' at the very beginning of the file.  Once I removed that, the error went away.  However, PetTracker still doesn't function correctly.  When I click on the world map and try to click the box for "Species" the box doesn't get checked, and the drop-down box just goes away.  Also, there is no search field.

**Comment by IGotThatToo** [comment]
I am getting the same lua error as raymbec32. The odd thing is that one of my characters, my main this expansion, is not getting this error. (Even though all my characters are using the same mod and settings) I am not sure if it's because Swatter gave up reporting it for that character. I have tried disabling all other mods, re-installing Pettracker, removed the Cache and WTF folders. All continue to produce the lua error above.

**Comment by sauljaffe** [comment]
FWIW, I just tried it on multiple characters (5) of different levels, different realms, different locations, both Alliance and Horde and I don't see any errors from PetTracker.  I'm using BugSack, btw to catch/report errors.

Maybe it's a conflict with another add-on you have?

**Comment by IGotThatToo** [comment]
I thought it might be a conflict as well but I tried this before with just Pettracker and Swatter installed. I am really puzzled. I tried the following again:
1. Scan and repair of Wow through launcher. (faster than re-install)
2. Removed all mods in addon folder except BugSack and Pettracker and the entire WTF Folder.
Still got the error on the characters I was getting the error on and not the 2 I wasn't. (High mountain druid and Dark Iron Shaman) (my 2nd dark iron shaman is getting the error)
4. Brand new characters do not give an error.
This is really weird and I think I am going to let it go for now. I will obsess over this later.

**Comment by sauljaffe** [comment]
I've spent a lifetime finding bugs in software that other people don't see and the developers often cannot reproduce so I sympathize with you.  It's almost always been something in my environment that is unique/different.  When you do go back to obsessing over this, try looking to see what the differences are between the two dark iron shamans.  The answer is probably there somewhere.  Good luck.

Hopefully by the time you come back to it, the developer of this add-on will have a new version out fixing all the problems.  I really like the add-on and found it very useful before 8.3 hit to find missing pets.  Right now though, it's almost useless for me.

**Comment by lissabunbun2** [comment]
I'm having the same issue with the map where I can't select species or the other two selections in that part. I disabled all my addons with only PetTracker active and that error occurred. Disabled PetTracker and the error went away where I can select options again. Basically tested it with no addons, map works fine. As long as PetTracker is active map part of choosing for filters won't work anymore.

**Comment by dblanch369** [comment]
I just love how the author has gone and disabled comments on the main page.  I think too many folks were griping.  Hopefully we will get some action on these issues soon.

**Comment by 180g** [comment]
I'm getting an almost identical error:

Stack: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:197: in function RestoreFilters' [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:376: in function _LoadPetsFinish'
[string "@interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:309: in function LoadPets' [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:422: in function ?'
[string "@interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>

**Comment by Spherikal** [comment]
Also getting this error. Anyone has a workaround fix?

**Comment by MSav93** [comment]
I'm also getting this error. From my short time testing a couple things it seems to only occur if a filter has been set on the PetJournal when logging in.

My best guess would be that the ClearFilters() function is not correctly recognising that there is a filter.

> 9x ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:197: ClearFilters() not called yet
> [string "=[C]"]: ?
> [string "@PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:197: in function `RestoreFilters'
> [string "@PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:376: in function `_LoadPetsFinish'
> [string "@PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:309: in function `LoadPets'
> [string "@PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:422: in function `?'
> [string "@PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>
> 
> Locals:
> (*temporary) = false
> (*temporary) = "ClearFilters() not called yet"

**Comment by sauljaffe** [comment]
When I get it, I don't have a filter set unless it's set somewhere in the background that just isn't visible now because I don't have a search/filter bar but I don't think so.

**Comment by aegrim2** [comment]
I got the apparently the same error as #86 , #143:

Message: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
Time: Wed Feb 12 09:38:16 2020
Count: 1
Stack: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:197: in function `RestoreFilters'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:376: in function `_LoadPetsFinish'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:309: in function `LoadPets'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:422: in function `?'
[string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>

Locals: 

Doesn't #131  "Fix :RestoreFilters called twice" give a hint solve the issue?

**Comment by SisterSkaoi** [comment]
Message when I'm logging in even if this is the only addon I'm loading. Has been occurring since 8.3 released.
Game version is 8.3.0.33369
Addon version for 8.3.0 released Jan 17 2020

> Message: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
> Time: Sun Feb 16 18:06:41 2020
> Count: 1
> Stack: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: ClearFilters() not called yet
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:197: in function `RestoreFilters'
> [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:376: in function `_LoadPetsFinish'
> [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:309: in function `LoadPets'
> [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:422: in function `?'
> [string "@Interface\AddOns\PetTracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua"]:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>
> 
> Locals:

**Comment by Jaliborc** [comment]
See PR 131
