### ISSUE TITLE
I can't mark the options

### ISSUE THREAD

**Issue by LuqxUnknow** [Jaliborc/PetTracker#140]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.0
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yes

**Describe the bug**
when i try to mark the options, like in "Zone traker" to show or not show captured pets, nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Zone tracker bar'
2. Click on 'left click'
4. See error 'nothing happens'

**Expected behaviour**

**Screenshots**
![Pettracker](https://user-images.githubusercontent.com/12689560/73127360-ca9e2a80-3f9d-11ea-911d-8ebb35241bb8.jpg)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**
that happens in any option, like the search in world map.
i already turned off all addons and that still happens
sorry about my english.

**Comment by satone** [comment]
I have exactly the same problem, only the Russian interface. I thought the error was due to the interface.

**Comment by dle0105** [comment]
I remember this issue existing a long time ago and eventually being fixed. Somehow it came back to annoy us, because I have the problem as well.

**Comment by jerksn** [comment]
having the same problem. disabled all addons but pettracker - all option, on world map and quest tracker are not interactable.

**Comment by paulywogs** [comment]
I've also been having this issue since the latest update. Similarly to the screenshot above I can't turn off Track Pets even though the options are there (they don't respond to my clicks). As you can see from my screenshot Track Pets is covering my World Quest Tracker and can't be turned off.
![Capture](https://user-images.githubusercontent.com/60820254/74087945-f2da5e80-4a5e-11ea-8f94-f9ab9f971041.JPG)

**Comment by Jaliborc** [comment]
Fixed
