### ISSUE TITLE
Unable to select pet species on map icon

### ISSUE THREAD

**Issue by morticianoire** [Jaliborc/PetTracker#142]
I am unable to select the pet species to highlight on map, i click on magnifyng glass, try to selet species and i can't do it, I don't know whats changed because i was able to do so before.
I have seen other reports but they say it disappears, mine doesnt I just cant select it

**Comment by clmcgrath** [comment]
also having this issue,  appears none of the dropdown lists are working

**Comment by woofpup** [comment]
I too have the same issue. Thanks for all you've done with an awesome addon.

**Comment by morticianoire** [comment]
Yes have to say I love the addon and I can still use it for other things
