### ISSUE TITLE
Better, but not perfect

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#145]
Well, apparently a new version was pushed through today (2/23/20).  It fixes a lot of the old bugs... but it's not perfect.  Some issues:

1.  I'm getting the tutorial messages again.  

2. I don't like having different icons for the different pets.  It makes the map too busy/complicated especially when showing other things from add-ons like Gathermate and Handynotes.  The simple paw print was best to make the pets stand out on the screen.

3.  No pets are showing up in Vale of Eternal Blossoms, especially when searching for missing pets.  I know I don't have several of the new BFA void pets like voidglower, and there's always supposed to be at least one in the zone but it doesn't show on my map.

**Comment by Jaliborc** [comment]
1. Settings were reworked and so the tutorial implementation. Expected behavior.
2. I can add an option for that.
3. The addon has been reworked, but the dataset hasn't been updated.

**Comment by sauljaffe** [comment]
1.  Maybe... but they are really annoying.  Most add-ons give you a way to turn off the tutorials and I believe the old version did as well.
2.  Thank you.
3.  Ok, so any idea when the dataset will be updated?

4. (new)  Even though I do not have the box for "switcher" checked in PetTracker, I still get PetTracker's switcher during pet battles.  This is a bug.
