### ISSUE TITLE
GetPetInfoByID(petGUID) error occurring after update.

### ISSUE THREAD

**Issue by Ookami313** [Jaliborc/PetTracker#146]
Updated to 8.3.1 and I'm receiving the following error after logging into the game.

Date: 2020-02-23 15:11:49
ID: 1
Error occured in: Global
Count: 1
Message: ...dOns\PetTracker\addons\main\classes\abstract\pet.lua line 154:
   Usage: GetPetInfoByID(petGUID)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: GetPetInfoByPetID()
   [string "@PetTracker\addons\main\classes\abstract\pet.lua"]:154: GetSpecie()
   [string "@PetTracker\addons\main\classes\abstract\pet.lua"]:93: GetAvailableBreeds()
   [string "@PetTracker\addons\journal\mods.lua"]:35: ModifyCard()
   [string "@PetTracker\addons\journal\mods.lua"]:29:
      PetTracker\addons\journal\mods.lua:29
   [string "=[C]"]: PetJournal_UpdatePetCard()
   [string "@Blizzard_Collections\Blizzard_PetCollection.lua"]:165:
      ...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:141
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by zalidthebur** [comment]
Same here.
