### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by Defuse7** [Jaliborc/PetTracker#147]
Getting the following error with the new version. Issue occurs on every zone change it seems. 

22x ...dOns\PetTracker\addons\main\classes\abstract\pet-Pet.lua:154: Usage: GetPetInfoByID(petGUID)
[string "=[C]"]: in function `GetPetInfoByPetID'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:154: in function `GetSpecie'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:93: in function `GetAvailableBreeds'
[string "@PetTracker\addons\journal\mods.lua"]:35: in function `ModifyCard'
[string "@PetTracker\addons\journal\mods.lua"]:29: in function <PetTracker\addons\journal\mods.lua:29>
[string "=[C]"]: in function `PetJournal_UpdatePetCard'
[string "@Blizzard_Collections\Blizzard_PetCollection.lua"]:165: in function <...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:141>

Locals:
(*temporary) = nil

**Comment by Incendio93** [comment]
I'm getting this exact error message too. I went through all my addons one by one with pet tracker and it appears to be conflicting with the Rarity addon.

**Comment by 12345566789** [comment]
1x ...Tracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:197: ClearFilters() not called yet
[string "=[C]"]: ?
[string "@PetTracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:197: in function `RestoreFilters'
[string "@PetTracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:376: in function `_LoadPetsFinish'
[string "@PetTracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:309: in function `LoadPets'
[string "@PetTracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:422: in function `?'
[string "@PetTracker\libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua"]:47: in function <...Tracker\libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>

Locals:
(*temporary) = false
(*temporary) = "ClearFilters() not called yet"
