### ISSUE TITLE
Addon Conflict

### ISSUE THREAD

**Issue by Tygerwyld** [Jaliborc/PetTracker#149]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.1

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Read it

**Describe the bug**
Installed the newest version of PetTracker (8.3.1). Once installed, noticed that another addon (Kaliel's Tracker; v3.21) no longer displayed/tracked my quests on screen. If I disabled the PetTracker, it seemed to work fine. However when they were both running together, only PetTracker seemed to work, and not the other.
Once I rolled back the update to the previous version of your addon, both seemed to be working once again. Uncertain what the conflict is.

**Comment by Markuz1965** [comment]
I have exactly the same issue. I have gone back to 8.3.0 and it works again. Obviously some conflict with Kaliel's tracker.

**Comment by Jaliborc** [comment]
Kaliel's Tracker actively provides PetTracker support, which is simply out of date. Nothing I can do here.

**Comment by Tygerwyld** [comment]
So basically have to wait for the tracker to be updated. Thanks for the
input anyway! Greatly appreciated

**Comment by Jaliborc** [comment]
Yup
