### ISSUE TITLE
Latest update breaks pet breeds on Rematch

### ISSUE THREAD

**Issue by Daervon** [Jaliborc/PetTracker#155]
As the title says, after the latest update, breeds are no longer shown in the Rematch journal window. Rolling back to 8.3.0 fixes this as well as the other journal issues introduced in 8.3.1.

No lua errors to report, at least for me.

**Comment by Kirbdawg** [comment]
Oh my god, this is a disaster!   Please bring back breeds!

**Comment by Jaliborc** [comment]
Is rematch an addon?

**Comment by Kirbdawg** [comment]
> Is rematch an addon?

Yes

**Comment by Jaliborc** [comment]
So, it appears Rematch is checking if PetTracker is installed (specifically, the deprecated PetTracker_Breeds). The integration will only work again when Rematch developer updates the addon to check for the new API location.

**Comment by Jaliborc** [comment]
I've sent a message to rematch developer on curseforge.
