### ISSUE TITLE
show/hide rivals tab; control what shows in pet tracker; add waypoints

### ISSUE THREAD

**Issue by darodriguesPT** [Jaliborc/PetTracker#158]
Thank you for adding the option to show specie icons or the old green paw! While it's easier to see where is what pet, my interface already has so many icons that it was getting harder to look (and i'm not missing more than a handful of wild pets at rare quality).

I'd like to ask for 3 options to be added:
1 - in Interface->Addons: hide the rivals tab (when i click it, it bugs out the pet journal because of rematch addon, and i really need this to battle faster and have teams);
2 - in Interface->Addons: control what shows in the pet tracker (example show only the bar, or hide pets at blue quality);
3 - in World Map: right clicking on the rival icon on the map show a menu with the option "Add this location to TomTom waypoints" like in HandyNotes.

This addon is great! Keep up the good work!
Thank you,
Dave

**Comment by alessandrouw** [comment]
These suggestions are really good. I really miss a way to customize the addon icons/size/scale. These options should be added whenever possible.

**Comment by Jaliborc** [comment]
please make each desired feature into a separate issue (so 4 total now), or I'll invetably forget the requests
