### ISSUE TITLE
Enemy ability CDs are gone

### ISSUE THREAD

**Issue by Arctagon** [Jaliborc/PetTracker#159]
It's nice to see that the addon has gone through a bit of an overhaul, but please don't remove the CD tracker for enemy pet abilities. I sorely need it. If it's a bug, I hope it can be fixed sooner rather than later. Its importance cannot be understated. It would also be nice with more options for customisation. I liked how it used to look.

**Comment by 12345566789** [comment]
Good if CD tracker for enemy pet abilities could be digital, like derrangement addon, not just gray.

**Comment by Bloodleh** [comment]
See the identical issue https://github.com/Jaliborc/PetTracker/issues/148, I posted a simple code fix for it yesterday.

**Comment by Gaviin1242** [comment]
I would appreciate a better fix than the one posted in #148.  That one puts a weird shaded box that is larger than the ability icons themselves.  And the cooldown numbers are too small.  Hoping this gets fixed from the addon creator.

Also, the ability icons themselves are way too small.  I'd appreciate a way to restore them to the size they were prior to this latest update.

**Comment by Bloodleh** [comment]
@Gaviin1242 I agree, the previous version's larger icons were way better. I just provided a fix to show them the way the author intended for this version :P

**Comment by v-radev90** [comment]
If you want to enlarge the icons and the CD text, first apply the [fix #148](https://github.com/Jaliborc/PetTracker/issues/148#issuecomment-590989248) by Bloodleh to enable the CD numbers. After that do the following:
Open and edit the abilityButton.xml file.
**addons\main\classes\combat\abilityButton.xml:**

Edit the following lines:
Line 3 to:
`<Size x="44" y="44"/>`

Line 10 to:
`<Size x="48" y="48"/>`

Line 24 to:
`<FontString parentKey="Cooldown" inherits="GameFontNormalHuge" hidden="true">`

Line 33 to:
`<Size x="35" y="35"/>`

Line 40 to:
`<Size x="22" y="22"/>`

Line 48 to:
`<Size x="22" y="22"/>`

If you want to further increase or reduce the size of the icons you can tweak the given numbers. For the CD text font you can edit the 'inherits' attribute value at Line 24 to another one. You can find some examples [here](https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/SharedXML/SharedFontStyles.xml).

**Comment by Gaviin1242** [comment]
Great fix, @v-radev90 !  Ability buttons and cd's look great for the active enemy pet.  Only downside is this seems to increase the size of the ability icons on the pet swap window too, making them too large there.  Oh well.  Maybe the author will separate the two settings at some point.
