### ISSUE TITLE
8.3.4 Battle cooldown

### ISSUE THREAD

**Issue by Endicott1378** [Jaliborc/PetTracker#160]
Addon version: 8.3.4

Changelog read

It seems battle cooldown still does not work

![image](https://user-images.githubusercontent.com/61589060/75553424-a6b88380-5a38-11ea-8a52-034cfe39424c.png)

**Comment by Jaliborc** [comment]
Ah shit

**Comment by Krovikan** [comment]
Same in my side.

I battle against Retinus the Seeker (eye in Uldum) and don't show the progress of cooldown of his abilities.

**Comment by Endicott1378** [comment]
At the same time, could you enlarge the squares, as in the old version 8.3.0 plz? I think that the majority will agree with me if I say that it was really more readable than the current version.

Thank you very much

**Comment by Krovikan** [comment]
I agree with you @Endicott1378
