### ISSUE TITLE
Multiple errors - no longer showing species

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#162]
I'm receiving multiple errors from the version of PetTracker pushed through on 2/27/20:

Error #1:
12x Couldn't open PetTracker\addons\main\main.xml

Error #2:
6x Couldn't open PetTracker_Breeds\PetTracker_Breeds.toc

Error #3:
6x Couldn't open PetTracker_Switcher\PetTracker_Switcher.toc

Error #4:
3x Couldn't open PetTracker\addons\journal\journal.xml

Error #5:
30x ...dOns\PetTracker\addons\main\classes\abstract\pet-Pet.lua:154: Usage: GetPetInfoByID(petGUID)
[string "=[C]"]: in function `GetPetInfoByPetID'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:154: in function `GetSpecie'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:93: in function `GetAvailableBreeds'
[string "@PetTracker\addons\journal\mods.lua"]:35: in function `ModifyCard'
[string "@PetTracker\addons\journal\mods.lua"]:29: in function <PetTracker\addons\journal\mods.lua:29>
[string "=[C]"]: in function `PetJournal_UpdatePetCard'
[string "@Blizzard_Collections\Blizzard_PetCollection.lua"]:117: in function <...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:114>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:50: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil

**Comment by Jaliborc** [comment]
Something wrong with your install
