### ISSUE TITLE
Enemy pet ability icons too small

### ISSUE THREAD

**Issue by Gaviin1242** [Jaliborc/PetTracker#164]
Per some comments in #159 , the newest version reduced the size of the active enemy pet ability icons too much.  There was a suggested fix in that issue ticket, which worked great for the active pet icons, but it also increased the size of the icons on the "switch pet" window, which doesn't look good... those should stay smaller.  Or at least add options to switch between the old larger icons and the new smaller ones in each of those contexts.

**Comment by Jaliborc** [comment]
I actually don't even know why they became smaller... lol
Will increase the size, no problem

**Comment by Gaviin1242** [comment]
Just downloaded the latest update, and looks perfect!  Thanks
