### ISSUE TITLE
Enemy cooldowns still doesn't work for me at least.

### ISSUE THREAD

**Issue by Skarra19** [Jaliborc/PetTracker#166]
**Running Software (issues missing this information will be deleted):**
 - Addon version: PetTracker-8.3.4-8.3.0.zip (Thats the name in twitch client)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. I did read the changelog yes

**Describe the bug**
Updated to 8.3.4 as the previous was bugged with the enemy cooldown. This version is still bugged for me. The enemy ability gets dimmed but the number does not show up in the small icon  (which also happened now..way to small icons) IF i revert to the 8.3.0 version of the addon the functionality comes back with cooldowns and the icons are normal again. I don't know if i can addd screenshots but i'll try:

This is from the new version (8.3.4)

![](https://i.gyazo.com/96a65ed62d20502b220c7d508f7d46bf.png)

And this is what i see in 8.3.0

![](https://i.gyazo.com/18c24be9123b5f3a1cfdab8aa016c943.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 8.3.4
2. Start game
3. Start petbattle and make enemy use ability
4. Be disappointed

**Expected behaviour**
I expected it to look as it does in the screenshot from 8.3.0

**Screenshots**
Well, hopefully they are up above, im new to github so excuse me if i did anything wrong :(.

**Comment by alessandrouw** [comment]
Can confirm, I'm using the updated addon (as of the time of this comment) and I cannot see enemy abilities CD

**Comment by Galthariel** [comment]
Same

**Comment by Skarra19** [comment]
After updating to 8.3.5 it once again works flawlessly (for me), thank you so much for your work.
