### ISSUE TITLE
Still bugs, still missing pets

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#173]
I deleted PetTracker and re-installed a clean copy using Twitch.

Error #1:
12x Couldn't open PetTracker\addons\main\main.xml

Error #2:
6x Couldn't open PetTracker_Breeds\PetTracker_Breeds.toc

Error #3:
6x Couldn't open PetTracker_Switcher\PetTracker_Switcher.toc

Error #4:
3x Couldn't open PetTracker\addons\journal\journal.xml

Error #5:
30x ...dOns\PetTracker\addons\main\classes\abstract\pet-Pet.lua:154: Usage: GetPetInfoByID(petGUID)
[string "=[C]"]: in function `GetPetInfoByPetID'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:154: in function `GetSpecie'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:93: in function `GetAvailableBreeds'
[string "@PetTracker\addons\journal\mods.lua"]:35: in function `ModifyCard'
[string "@PetTracker\addons\journal\mods.lua"]:29: in function <PetTracker\addons\journal\mods.lua:29>
[string "=[C]"]: in function `PetJournal_UpdatePetCard'
[string "@Blizzard_Collections\Blizzard_PetCollection.lua"]:117: in function <...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:114>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:50: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil

In addition, PetTracker is not showing ANY species in Vale of Eternal Blossoms or Uldum.  And it's definitely not showing missing Species in either location.  I know I'm missing one or two in each.  For example, I know I'm missing Golden Chirper in Vale of Eternal Blossoms.

Please do not close this report without addressing these issues.  Closing them without comment helps no one.

**Comment by Jaliborc** [comment]
Please read the changelog, your install is corrupted

**Comment by sauljaffe** [comment]
Please read the post:

I deleted PetTracker and did a clean install.

THE INSTALL IS NOT CORRUPTED.  THESE ARE BUGS.

> On Mar 1, 2020, at 10:54 AM, João Cardoso <notifications@github.com> wrote:
> 
> Please read the changelog, your install is corrupted
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990

**Comment by hdidier** [comment]
@sauljaffe I had a similar problem, but the issue I had was with another pet related addon.  Have you also deleted ALL other addons and tried with ONLY PetTracker installed?  I noticed in the error outputs you have removed all of your other installed addons.
CC: @Jaliborc

**Comment by sauljaffe** [comment]
The only other pet related add ons I use are BattlePetBreedID and Rematch.  Rematch doesn't do anything on the map as far as I know - it's just for battles themselves.  BattlePetBreedID might or might not - I'm not sure.  In any case, I disabled them both and it made no difference.
