### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by GamerDave74** [Jaliborc/PetTracker#19]
I installed the addon and it initially worked fine but a day later I now get the following

----> 

Date: 2017-11-26 13:32:03
ID: 1
Error occured in: Global
Count: 1
Message: ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua line 197:
   ClearFilters() not called yet
Debug:
   [C]: ?
   ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:197: RestoreFilters()
   ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:376: _LoadPetsFinish()
   ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:309: LoadPets()
   ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:422: ?()
   ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:47:
      ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46
Locals:
(*temporary) = false
(*temporary) = "ClearFilters() not called yet"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  Altoholic, vr183
  AtlasLoot, vv8.07.05
  AtlasLootBurningCrusade, vv8.07.05
  AtlasLootCataclysm, vv8.07.05
  AtlasLootClassic, vv8.07.05
  AtlasLootLegion, vv8.07.05
  AtlasLootMistsofPandaria, vv8.07.05
  AtlasLootWarlordsofDraenor, vv8.07.05
  AtlasLootWrathoftheLichKing, vv8.07.05
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  Configator, v5.1.DEV.431(/embedded)
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v7.3.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  EnchantrixBarker, v7.5.5724 (TasmanianThylacine)
  Gatherer, v7.3.1
  Informant, v7.5.5724 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.430(/embedded)
  NPCScan, v7.3.0.6
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Recount, vv7.3.2a
  SlideBar, v7.3.1 (<%codename%>)
  Stubby, v7.5.5724 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=b39)

Now I have uninstalled, reinstalled, installed, deleted folders, uninstalled, delete settings all of the above and it continues.

**Comment by SilentStorm01** [comment]
I also get an error every time I log in.

34x ...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:197: ClearFilters() not called yet
[C]: ?
...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:197: in function `RestoreFilters'
...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:376: in function `_LoadPetsFinish'
...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:309: in function `LoadPets'
...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:422: in function `?'
...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0-31.lua:47: in function <...Tracker\Libs\LibPetJournal-2.0\LibPetJournal-2.0.lua:46>

Locals:
(*temporary) = false
(*temporary) = "ClearFilters() not called yet"

**Comment by vuruba** [comment]
Yes, I have it too

Message: Interface\AddOns\PetTracker\Features\Objectives.lua:78: attempt to perform arithmetic on field 'contentsHeight' (a nil value)
Time: 12/07/17 13:25:06
Count: 1
Stack: Interface\AddOns\PetTracker\Features\Objectives.lua:78: attempt to perform arithmetic on field 'contentsHeight' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
Interface\AddOns\PetTracker\Features\Objectives.lua:78: in function `GetUsedHeight'
Interface\AddOns\PetTracker\Features\Objectives.lua:48: in function <Interface\AddOns\PetTracker\Features\Objectives.lua:47>
[C]: in function `ObjectiveTracker_Update'
[string "*:OnLoad"]:4: in function `setFunc'
Interface\FrameXML\InterfaceOptionsPanels.lua:89: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:85>
[C]: in function `pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:217: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:216>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:252: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:248>

Locals: errorMessage = "Interface\AddOns\PetTracker\Features\Objectives.lua:78: attempt to perform arithmetic on field 'contentsHeight' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
