### ISSUE TITLE
PetTracker 7.1.4 hiding options, that control which World Quests are visible.

### ISSUE THREAD

**Issue by LovisMirac** [Jaliborc/PetTracker#2]
With PetTracker turned off -- seeing the default operation of WoW 7.2.0.23937 (updated 4/18/2017) -- going to WoW's main map (clicking "M"), and clicking the main map's hourglass (on the top right), while looking at any Broken Isles' zone, the hourglass drop-down shows you options for which world quests are visible.  The bottom half of those options has a title of "World Quest Rewards"... for example letting me uncheck Order Resources, Artifact Power, Profession Materials, and Gold... to only show Equipment world quests, if I want.
 
But with PetTracker 7.1.4 turned on, and WoW's UI reloaded, that bottom half of the world quest controls does not show:  there is no title of "World Quest Rewards", and none of the options that I listed above, in my example, are shown.

**Comment by mluks** [comment]
I second this.  It took me forever to figure out why I had so few world quests on the map until I figured out those options were hidden and I couldn't unfilter the world quests.  Turning off PetTracker returns the filtering options.
