### ISSUE TITLE
Rival History Lua Error

### ISSUE THREAD

**Issue by gitIntruder** [Jaliborc/PetTracker#206]
When going to the Rivals subtab then click on the history button at the top right I get the following error.

Message: ...nterface\AddOns\PetTracker\addons\journal\record.lua:74: attempt to perform arithmetic on local 'date' (a string value)
Time: Fri Aug 14 07:29:45 2020
Count: 2
Stack: ...nterface\AddOns\PetTracker\addons\journal\record.lua:74: attempt to perform arithmetic on local 'date' (a string value)
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:74: in function `UnpackDate'
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:58: in function `Unpack'
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:28: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:265: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:187: in function `Update'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:125: in function `SetTab'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: self = <unnamed> {
 NormalTexture = <unnamed> {
 }
 HighlightTexture = <unnamed> {
 }
 won = true
 Selected = <unnamed> {
 }
 Content = <unnamed> {
 }
 0 = <userdata>
}
date = "99e"
yearDate = 230
(*temporary) = 14
(*temporary) = 8
(*temporary) = <function> defined =[C]:-1
(*temporary) = 7
(*temporary) = "attempt to perform arithmetic on local 'date' (a string value)"

**Comment by tazrulez** [comment]
I have a similar error when I open the rivals tab:

3x PetTracker\addons\journal\record.lua:74: attempt to perform arithmetic on local 'date' (a string value)
[string "@PetTracker\addons\journal\record.lua"]:74: in function `UnpackDate'
[string "@PetTracker\addons\journal\record.lua"]:58: in function `Unpack'
[string "@PetTracker\addons\journal\record.lua"]:28: in function `Display'
[string "@PetTracker\addons\journal\rivals.lua"]:265: in function `Display'
[string "@PetTracker\addons\journal\rivals.lua"]:187: in function `Update'
[string "@PetTracker\addons\journal\rivals.lua"]:98: in function `SetRival'
[string "@PetTracker\addons\journal\rivals.lua"]:87: in function <PetTracker\addons\journal\rivals.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetShown'
[string "@PetTracker\libs\SecureTabs-2.0\SecureTabs-2.0-2.lua"]:91: in function `Update'
[string "@PetTracker\addons\journal\rivals.lua"]:129: in function `Open'
[string "@PetTracker\addons\journal\rivals.lua"]:95: in function `SetRival'
[string "@PetTracker\addons\main\classes\abstract\rival.lua"]:55: in function `Display'
[string "@PetTracker\addons\main\features\gossip.lua"]:47: in function <...cePetTracker\addons\main\features\gossip.lua:44>
[string "=[C]"]: in function `SelectGossipOption'
[string "@FrameXML\GossipFrame.lua"]:131: in function <FrameXML\GossipFrame.lua:125>
[string "=[C]"]: in function `GossipTitleButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = <unnamed> {
 NormalTexture = <unnamed> {
 }
 HighlightTexture = <unnamed> {
 }
 won = true
 Selected = <unnamed> {
 }
 Content = <unnamed> {
 }
 0 = <userdata>
}
date = "90b"
yearDate = 83
(*temporary) = 22
(*temporary) = 3
(*temporary) = <function> defined =[C]:-1
(*temporary) = 2
(*temporary) = "attempt to perform arithmetic on local 'date' (a string value)"

**Comment by soundblaster32** [comment]
Getting the same error as well. Tried uninstalling and reinstalling the addon manually from Curse and still had the same issue. Reinstalled the addon from twitch and was able to view the tab but after one pet battle with a tamer, received a similar error:

Message: ...nterface\AddOns\PetTracker\addons\journal\record.lua:74: attempt to perform arithmetic on local 'date' (a string value)
Time: Sun Oct 11 21:54:26 2020
Count: 3
Stack: ...nterface\AddOns\PetTracker\addons\journal\record.lua:74: attempt to perform arithmetic on local 'date' (a string value)
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:74: in function `UnpackDate'
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:58: in function `Unpack'
[string "@Interface\AddOns\PetTracker\addons\journal\record.lua"]:28: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:265: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:187: in function `Update'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:125: in function `SetTab'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: self = <unnamed> {
 NormalTexture = <unnamed> {
 }
 HighlightTexture = <unnamed> {
 }
 won = true
 Selected = <unnamed> {
 }
 Content = <unnamed> {
 }
 0 = <userdata>
}
date = "9d9"
yearDate = 289
(*temporary) = 11
(*temporary) = 10
(*temporary) = <function> defined =[C]:-1
(*temporary) = 9
(*temporary) = "attempt to perform arithmetic on local 'date' (a string value)"
