### ISSUE TITLE
Tooltip redundancy and overlap with Rarity

### ISSUE THREAD

**Issue by DenL** [Jaliborc/PetTracker#210]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.8
 - Server patch: 8.3.7 35662

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Both Rarity and Pettracker add "Drop" and "Zone" information to caged pets tooltip. Having both enabled will cause tooltip to display same information twice like this:
![image](https://user-images.githubusercontent.com/5632219/93575423-9da4ea80-f967-11ea-92f8-f421c3cb5e1b.png)

If you mouseover a caged pet in the auction house buy interface, it would cause overlap with "Seller" line like this:
![image](https://user-images.githubusercontent.com/5632219/93575468-af868d80-f967-11ea-896e-ba1b5c70e56e.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Mouse over any caged pet
2. Mouse over any caged pet in AH buy interface

**Expected behaviour**
No tooltip overlap or redundancy. Perhaps an option to disable source tooltip on caged pets.

**Screenshots**
See above

**Error Logs**
N/A

**Additional context**
N/A

**Comment by Jaliborc** [comment]
Pretty sure #203 fixed this
