### ISSUE TITLE
PetTracker_Broker tooltip does not display species list

### ISSUE THREAD

**Issue by DenL** [Jaliborc/PetTracker#211]
**Running Software (issues missing this information will be deleted):**
 - Addon version: PetTracker_Broker-8.0.1-8.3.0.zip
 - Server patch: 8.3.7 35662

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Databroker tooltip only has the pet progress bar. It does not have the species list like in the main PetTracker tracker.

**To Reproduce**
Steps to reproduce the behaviour:
1. Mouseover the databroker display to show tooltip

**Expected behaviour**
Tooltip has species list like in the screenshot on curseforge
![image](https://user-images.githubusercontent.com/5632219/93584049-c54d8000-f972-11ea-92e3-f4a2ebf8b966.png)

**Screenshots**
Tooltip has tracker bar only
![image](https://user-images.githubusercontent.com/5632219/93584117-dbf3d700-f972-11ea-9413-4596819ba6eb.png)

**Error Logs**
No script error

**Additional context**
N/A

**Comment by wadergirl** [comment]
![image](https://user-images.githubusercontent.com/72587392/95534122-a27b1e00-09aa-11eb-8eb9-c3325f6cee19.png)
Same issue here.  Using with ChocolateBar.

**Comment by Jaliborc** [comment]
Fixed
