### ISSUE TITLE
PvP is still not working.  

### ISSUE THREAD

**Issue by scottish-kat** [Jaliborc/PetTracker#212]
I raised an issue with PvP pet battles 6 pet events ago and it's still not working.  Please can you let me know if this is ever going to be fixed or at the very least made consistent. 

thanks

**Comment by BenBelatrix** [comment]
I have the same problem - had to install back version 8.3.0

**Comment by beth82014** [comment]
I have also been having this issue for a long while.  Can confirm going back to version 8.3.0 does fix it. Thanks for that advice, been driving me nut in PVP. Hopefully this will get fixed before SL.

**Comment by scottish-kat** [comment]
Was this closed because you fixed it (it's not fixed on 9.0.1 - I can send screenshots) or because you have no intention of fixing it?

**Comment by BenBelatrix** [comment]
I have to confirm it (in 9.0.1) - there are still problems in PVP. Sometimes addons reload helps...

**Comment by scottish-kat** [comment]
I have re-installed, reloaded both multiple times.  PVP is still broken

**Comment by BenBelatrix** [comment]
Try to delete all PetTracker folders from World of Warcraft\_retail_\Interface\AddOns and install new version. I'm testing is only with this adddon + Rematch and have no more troubles in PVP...

**Comment by beth82014** [comment]
Tried again this morning. Delete file from Addons folder, reinstalled,
turned everything off but Rematch and Pet Tracker, still same issue exactly
as before.
