### ISSUE TITLE
9.0.1 rivals functionality gives "attempt to call global 'IsQuestFlaggedCompleted'"

### ISSUE THREAD

**Issue by spiralofhope** [Jaliborc/PetTracker#215]
**Running Software (issues missing this information will be deleted):**

- Addon version: 8.3.8
 - Server patch:  9.0.1.36230

 **Have you read the changelog? (please don't waste our time)**
Mark if read. [x] yes

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Pet Journal
2. Click on `Rivals`
3. See error

**Expected behaviour**

When selecting a rival in the left column, no entries are seen in the right-hand area.  For example, all pet slots say "Pet missing"

**Screenshots**

![WoWScrnShot_101420_110551](https://user-images.githubusercontent.com/492880/96027893-6feb7e00-0e0d-11eb-864b-f908f5f3f1ad.jpg)

**Error Logs**

> Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

I'm not sure I understand these instructions.  The error popup does not change after this slash command.

<details>
 <summary>Click to expand</summary>

```
Message: ...ns\PetTracker\addons\main\classes\abstract\rival.lua:94: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
Time: Wed Oct 14 11:04:39 2020
Count: 1
Stack: ...ns\PetTracker\addons\main\classes\abstract\rival.lua:94: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
[string "@Interface\AddOns\PetTracker\addons\main\classes\abstract\rival.lua"]:94: in function `IsCompleted'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:206: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:173: in function `Update'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:98: in function `SetRival'
[string "@Interface\AddOns\PetTracker\addons\journal\rivals.lua"]:87: in function <...nterface\AddOns\PetTracker\addons\journal\rivals.lua:31>
[string "=[C]"]: in function `SetShown'
[string "@Interface\AddOns\PetTracker\libs\SecureTabs-2.0\SecureTabs-2.0.lua"]:91: in function `Update'
[string "@Interface\AddOns\PetTracker\libs\SecureTabs-2.0\SecureTabs-2.0.lua"]:64: in function `Select'
[string "@Interface\AddOns\PetTracker\libs\SecureTabs-2.0\SecureTabs-2.0.lua"]:42: in function <...ns\PetTracker\libs\SecureTabs-2.0\SecureTabs-2.0.lua:42>

Locals: self = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 items = ""
 map = 37
 name = "Julia Stevens"
 gold = 3
 id = 64330
 model = 1691
 quest = 31693
 currencies = ""
}
(*temporary) = nil
(*temporary) = 31693
(*temporary) = "attempt to call global 'IsQuestFlaggedCompleted' (a nil value)"
</details>

**Comment by ObiWahn86** [comment]
There should be "C_QuestLog." in front of "IsQuestFlaggedCompleted".

So to fix this change line 94 in:

"...\Interface\AddOns\Pettracker\addons\main\classes\abstract\rivals.lua"

from

`	return IsQuestFlaggedCompleted(self.quest)`

to

`	return C_QuestLog.IsQuestFlaggedCompleted(self.quest)`

**Comment by spiralofhope** [comment]
Thanks @ObiWahn86 I've added those changes to the pull requests.

I still see an error on login though, but it appears to be separate.

Closing this, for cleanliness.
