### ISSUE TITLE
Seeing the following error

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#216]
1x ...ker\libs\CustomTutorials-2.1\CustomTutorials-2.1-10.lua:150: attempt to call method 'SetBackdrop' (a nil value)
[string "@PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1-10.lua"]:150: in function <...ker\libs\CustomTutorials-2.1\CustomTutorials-2.1.lua:125>
[string "@PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1-10.lua"]:181: in function `RegisterTutorials'
[string "@PetTracker\addons\config\tutorials.lua"]:43: in function `Load'
[string "@PetTracker\addons\config\tutorials.lua"]:27: in function `?'
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@PetTracker\addons\main\main.lua"]:46: in function `?'
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@FrameXML\UIParent.lua"]:1373: in function <FrameXML\UIParent.lua:1258>

This is after applying the patch/changes as recommended in this thread:
https://github.com/Jaliborc/PetTracker/issues/213#issuecomment-708576526

**Comment by spiralofhope** [comment]
I might have solved that:

https://github.com/spiralofhope/CustomTutorials-2.1/commit/d73286564635cc5f5dfa6106eb3e45666ae3e756

Does that change work for you?

I can't test this problem because I don't know how to reproduce it.

**Comment by sauljaffe** [comment]
Yes, I think it did.  Thank you.

I’ll know for sure tomorrow - I’m done for today. 

> On Oct 14, 2020, at 3:32 PM, spiralofhope <notifications@github.com> wrote:
> 
> 
> I might have solved that:
> 
> spiralofhope/CustomTutorials-2.1@d732865
> 
> Does that change work for you?
> 
> I can't test this problem because I don't know how to reproduce it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990
