### ISSUE TITLE
Function C_Calendar.GetDate() was removed from the API

### ISSUE THREAD

**Issue by ObiWahn86** [Jaliborc/PetTracker#217]
The function C_Calendar.GetDate() was marked deprecated in 8.1.0 and is now removed in 9.0.1.

line 101 in:

...Interface\AddOns\PetTracker\addons\battle\listener.lua

must be changed from

`	local date = C_Calendar.GetDate()`

to

`	local date = C_DateAndTime.GetCurrentCalendarTime()`

**Comment by Jaliborc** [comment]
Gotcha! Thanks!
