### ISSUE TITLE
not working lua error

### ISSUE THREAD

**Issue by rhainstorm** [Jaliborc/PetTracker#218]
Message: ...ce\AddOns\PetTracker\addons\main\features\gossip.lua:44: hooksecurefunc(): SelectGossipOption is not a function
Time: Wed Oct 14 17:28:03 2020
Count: 1
Stack: ...ce\AddOns\PetTracker\addons\main\features\gossip.lua:44: hooksecurefunc(): SelectGossipOption is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\PetTracker\addons\main\features\gossip.lua"]:44: in function `?'
[string "@Interface\AddOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@Interface\AddOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface\AddOns\BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...igs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\BigWigs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>
Message: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
Time: Wed Oct 14 17:28:06 2020
Count: 1
Stack: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\PetTracker\addons\main\features\objectives.lua"]:78: in function `GetUsedHeight'
[string "@Interface\AddOns\PetTracker\addons\main\features\objectives.lua"]:48: in function <...ddOns\PetTracker\addons\main\features\objectives.lua:47>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:937: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:936>
[string "=[C]"]: in function `GetHeight'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1339: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1325>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:917: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:835>

Locals: 
Message: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
Time: Wed Oct 14 17:28:06 2020
Count: 1
Stack: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\PetTracker\addons\main\features\objectives.lua"]:78: in function `GetUsedHeight'
[string "@Interface\AddOns\PetTracker\addons\main\features\objectives.lua"]:48: in function <...ddOns\PetTracker\addons\main\features\objectives.lua:47>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:917: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:835>

Locals: 

any fix? i have shadowlands pre and elvui

**Comment by ObiWahn86** [comment]
A fix was posted by fuba82 in #213.
