### ISSUE TITLE
Moving search bar on worldmap

### ISSUE THREAD

**Issue by Starfighter7201** [Jaliborc/PetTracker#226]
**Is your feature request related to a problem? Please describe.**
On the worldmap, the searchbar overlaps with several icons created by other addons.

**Describe the solution you'd like**
I would be able to move or hide the searchbar on the worldmap

**Describe alternatives you've considered**
Asking the authors of addons that create to overlapped icons to make their icons moveable.

**Additional context**
![image](https://user-images.githubusercontent.com/64983999/96335976-9bc06b00-107c-11eb-84d8-12e2665c5a4d.png)

**Comment by Jaliborc** [comment]
Fixed in beta build
