### ISSUE TITLE
List of pets under the list of quest is not displayed anymore

### ISSUE THREAD

**Issue by Xandoria** [Jaliborc/PetTracker#227]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.0.1 dated 16 oct 2020
 - Server patch: 9.0.1 (36272) (serie x64)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read : yes

**Describe the bug**
The list of pets in the region I am in which is usually displayed under th list of quest is not displayed anymore. I had to reinstall previous version of the addon to see it again.

**Additional context**
I am using the French language version of the game, but I don't think it is relevant.

**Comment by iamweaver** [comment]
I see a pet list when I am in Deepholm (away from the temple), and I see it there on multiple alts. But so far that is the only zone I have found that shows the acquired pet list.  I took a griffon flight from Theramore to Winterspring, and none of the intervening zones triggered the list.

**Comment by Sathorn** [comment]
I have the same issue, but you have to know that I am using ElvUI, which may have impact on this problem.

**Comment by BradMJustice** [comment]
Confirming that I also experienced this issue on 10/19/2020 with version 9.0.1. Reverting to 9.0.0 fixed the issue.

**Comment by Elyssian** [comment]
I am having the same issue. List not showing up under quests. If I go to my addons and uncheck Pet Tracker config or journal, reload UI, the list will come back  until I use a portal and leave the zone. I have to go back in and do the same steps to pull it back up. This happens regardless of any other addons.

**Comment by Elyssian** [comment]
I added a reload UI button to my titan panel (for convenience) and the list shows up after a reload. I will just do that in each area until a fix is updated.

**Comment by Kharsis** [comment]
I am having this issue also.  Pet Tracker is not showing pets to capture in each zone.

**Comment by virtuoz75** [comment]
Thanks @Elyssian using typing "/reload" is actually working for me. I guess there will be a fix to do on Pet Tracker, seems to be an issue from the addon

**Comment by DreamOfHero** [comment]
I found a workaround.
after opening and enter into character you have to deactivate all Add-ons, reload, activate all addon back, reload...
Reload only don't work many time.

I found also that the zone Tracker disappear often when you enter in a sub-zone (like a cave) and reappear only if I deactivate  and reactivate all addons..
