### ISSUE TITLE
LUA Error in 9.02 beta

### ISSUE THREAD

**Issue by ghuff07** [Jaliborc/PetTracker#233]
2x PetTracker\addons\config\tutorials.lua:41: attempt to index local 'mapSearchBox' (a boolean value)
[string "@PetTracker\addons\config\tutorials.lua"]:41: in function `?'
[string "@PetTracker\addons\config\tutorials.lua"]:163: in function <PetTracker\addons\config\tutorials.lua:162>
[string "=[C]"]: ?
[string "=[C]"]: in function `resume'
[string "@DugisGuideViewerZ\LuaUtils.lua"]:439: in function <DugisGuideViewerZ\LuaUtils.lua:429>
[string "@DugisGuideViewerZ\LuaUtils.lua"]:528: in function <DugisGuideViewerZ\LuaUtils.lua:508>

Locals:
self = <table> {
 SendSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 HookShown = <function> defined @PetTracker\addons\config\tutorials.lua:157
 RegisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 TriggerOn = <function> defined @PetTracker\addons\config\tutorials.lua:153
 ResetTutorials = <function> defined @PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1.lua:204
 SendMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
  = true
 UnregisterSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:78
  = true
  = true
 Load = <function> defined @PetTracker\addons\config\tutorials.lua:39
 RegisterSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 TriggerTutorial = <function> defined @PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1.lua:187
 NewModule = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RegisterEvent = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 OnEnable = <function> defined @PetTracker\addons\config\tutorials.lua:26
 GetTutorials = <function> defined @PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1.lua:219
 UnregisterAllEvents = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Start = <function> defined @PetTracker\addons\config\tutorials.lua:35
 RegisterTutorials = <function> defined @PetTracker\libs\CustomTutorials-2.1\CustomTutorials-2.1.lua:176
 UnregisterEvent = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Tag = "PETTRACKER_"
}
mapSearchBox = true
(*temporary) = WorldMapFrame {
 HandleUserActionOpenQuestLog = <function> defined @FrameXML\QuestLogOwnerMixin.lua:84
 ShouldPanOnClick = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:656
 GetMinZoomViewRect = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:676
 PanTo = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:623
 HandleUserActionOpenSelf = <function> defined @FrameXML\QuestLogOwnerMixin.lua:91
 AreDetailLayersLoaded = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:433
 RemovePin = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:207
 OnCanvasScaleChanged = <function> defined =[C]:-1
 RemoveGlobalPinMouseActionHandler = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:808
 OnQuestLogOpen = <function> defined @FrameXML\QuestLogOwnerMixin.lua:219
 CalculatePinNudging = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:326
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:579
 ApplyPinPosition = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:491
 SetAreaTriggerIntersectsCallback = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:272
 ShouldZoomInstantly = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:664
 HandleUserActionToggleQuestLog = <function> defined @FrameXML\QuestLogOwnerMixin.lua:44
 NavBar = <unnamed> {
 }
 pinNudgingDirty = true
 SetGlobalPinScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:866
 RefreshDeb

**Comment by Addonman** [comment]
Count: 1
Message: ...erface\AddOns\PetTracker\addons\config\tutorials.lua line 41:
   attempt to index local 'mapSearchBox' (a boolean value)
Debug:
   [string "=(tail call)"]: ?
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=[C]"]: ?
   [string "@PetTracker\addons\config\tutorials.lua"]:41: ?()
   [string "@PetTracker\addons\config\tutorials.lua"]:163:
      ...erface\AddOns\PetTracker\addons\config\tutorials.lua:162
   [string "=[C]"]: ?
   [string "=[C]"]: Show()
   [string "@..\FrameXML\UIParent.lua"]:3450:
      ..\FrameXML\UIParent.lua:3436
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ShowUIPanel()
   [string "@..\FrameXML\QuestLogOwnerMixin.lua"]:103:
      ..\FrameXML\QuestLogOwnerMixin.lua:99
   [string "=[C]"]: SetDisplayState()
   [string "@..\FrameXML\QuestLogOwnerMixin.lua"]:41: HandleUserActionToggleSelf()
   [string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:435:
      ...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:434
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ToggleWorldMap()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1
Locals:
(*temporary) = "down"
(*temporary) = <function> defined =[C]:-1
