### ISSUE TITLE
No pets showing up on Map - Maw/Korthia

### ISSUE THREAD

**Issue by ghost** [Jaliborc/PetTracker#266]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.0
 - Server patch: 9.1.0 (39262)

I have enabled Pet Tracker with all dependencies, but I am not seeing any pet icons display on the map. I am looking specifically in The Maw and Korthia where I know I have not captured pets. 

**To Reproduce**
Enable Pet Tracker - view map for The Maw/Korthia.

![pettracker](https://user-images.githubusercontent.com/52841691/124291139-3f29b100-db22-11eb-9f4a-6f4395c932fd.jpg)
![korthia](https://user-images.githubusercontent.com/52841691/124291144-405ade00-db22-11eb-8699-02b31cdb1025.jpg)

**Error Logs**
Nothing showed up when I did this.

I have tried re-installing PetTracker as well. Is there something I'm missing?

**Comment by CatCooperman** [comment]
I'm having the exact same problem. I also tried the things you tried. I don't see the tracker under the quest log, and when I installed PetTracker Broker and set it up in TitanPanel, it shows "0/0" pets regardless of the zone I'm in.

**Comment by sharpzzz** [comment]
Same problem.

Id also like to suggest not making anymore addons if you cant support them. The fact that this issue was posted 3 weeks ago and has gotten ZERO help is ridiculous. This seems to be what most addon authors do. Create addon & dissappear. Just dont make them.

**Comment by tonecool** [comment]
Same problem here. Is this even working for anyone? Maybe addon is just lying about being updated to 9.1.

**Comment by Jasmynne** [comment]
Same problem here. Is this even working for anyone?

**Comment by Niteowlpc** [comment]
Still the same problem in November

**Comment by Natheedo** [comment]
Same problem here!

**Comment by FrakBT** [comment]
I am having this issue as well.
