### ISSUE TITLE
Map pet icons problems

### ISSUE THREAD

**Issue by electroRaccoon** [Jaliborc/PetTracker#272]
in 9.1.5, you can't hide pet icons on the maps. the whole ui has been modified so the hide/show pet drop drown menu don't work anymore.

**Comment by NaomiErin** [comment]
Same here. There is no option to show/hide pets via the magnifying glass on the world map anymore!

**Comment by Acidfrost59** [comment]
I am also having this problem. I went to look at the various Lua files. They have this disclaimer: As a special exception, the copyright holders of this addon do not give permission to redistribute and/or modify it.
Hopefully, Jaliborc (João Cardoso) is doing well and is interested in continuing to maintain this add-on.

**Comment by oznogon** [comment]
The current version of the addon, 9.1.2, released today no longer has this issue. The magnifying glass icon's menu on the world map has restored the filter and icon toggles.

![image](https://user-images.githubusercontent.com/19192104/144701210-a6c967d6-cc1a-4ad0-a62a-501df1e1d99e.png)

**Comment by Acidfrost59** [comment]
Thank you! I definitely appreciate your add-on.
