### ISSUE TITLE
Just a question?

### ISSUE THREAD

**Issue by NaomiErin** [Jaliborc/PetTracker#273]
Does anyone know if this add-on is still being maintained? 

This has been a welcome addition to my addon family for some time now but lately, it just doesn't function as intended. I can't hide the pet icons on the map, there is no search function and no pet section in the magnifying/ dropdown at the top right of the world may interface.

**Comment by Mike160770** [comment]
I wrote a note to the author 3 weeks ago, but got no answer so far - although he seems to be online every few days.

**Comment by NaomiErin** [comment]
> I wrote a note to the author 3 weeks ago, but got no answer so far - although he seems to be online every few days.

Yeah, I assumed he has moved on so have nlw uninstalled it and am in search of an adequate replacement. It's a shame really because my husband and I are both avid pet collectors and absolutely relied on this addon. Regardless I wish the author the best amd appreciate the many years of help he provided x

**Comment by Mike160770** [comment]
> > I wrote a note to the author 3 weeks ago, but got no answer so far - although he seems to be online every few days.
> 
> Yeah, I assumed he has moved on so have now uninstalled it and am in search of an adequate replacement. It's a shame really because my husband and I are both avid pet collectors and absolutely relied on this addon. Regardless I wish the author the best amd appreciate the many years of help he provided x

Were you successful in finding an alternative add-on?

**Comment by NaomiErin** [comment]
> > > I wrote a note to the author 3 weeks ago, but got no answer so far - although he seems to be online every few days.
> > 
> > 
> > Yeah, I assumed he has moved on so have now uninstalled it and am in search of an adequate replacement. It's a shame really because my husband and I are both avid pet collectors and absolutely relied on this addon. Regardless I wish the author the best amd appreciate the many years of help he provided x
> 
> Were you successful in finding an alternative add-on?

Unfortunately not. There are quite a few out there but none can do what Pet Tracker does. However, the search continues.

**Comment by addonaddict** [comment]
Author does not seem to care. Asked numerous time to fix a braindead-easy bug and they just close it without a word. Someone should make an alternative or takeover.

**Comment by Jaliborc** [comment]
it is
