### ISSUE TITLE
Portrait strata bug

### ISSUE THREAD

**Issue by addonaddict** [Jaliborc/PetTracker#279]
Can you please fix the strata on the portraits?
This was reported over a year ago, seems like one of the easiest things to fix
If you're not interested in this, could you let me know what to adjust in the code so I can do it myself?
Thanks

![image](https://user-images.githubusercontent.com/73442541/160206402-7b568407-0e08-4b75-8a4a-3d2028bd1caa.png)

**Comment by addonaddict** [comment]
Thanks for closing without a word. I guess programmers these days are too stupid / lazy to make a quality product. Deleting.

**Comment by Jaliborc** [comment]
Thank you for your opinion. It ain't the strata.

**Comment by addonaddict** [comment]
You're welcome. I hope someone helps you fix this, as you clearly just called it quits.
