### ISSUE TITLE
Duplicate Breed Icon on Pet Name (First Line) for Caged Pets

### ISSUE THREAD

**Issue by Galthariel** [Jaliborc/PetTracker#282]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Duplicate Breed Icon on Pet Name (First Line) for Caged Pets

**To Reproduce**
1. Go to Bags
2. Mouse Over a Caged Pet
3. It shows Duplicate Breed Icon on Pet Name (First Line) for Caged Pets
4. No Error

**Expected behaviour**
To show Breed Icon on Pet Name (First Line) for Caged Pets only once

**Screenshots**
(https://ibb.co/bJ6km7q)

**Error Logs**
None

**Additional context**
None

**Comment by Jaliborc** [comment]
You have another mod enabled showing the breeds
