### ISSUE TITLE
Map Tooltip Not Scaling with UI Scale

### ISSUE THREAD

**Issue by BornabeWylde** [Jaliborc/PetTracker#290]
**Running Software:**
 - Addon version:  9.2.0
 - Server patch: Retail 9.2.7

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the Bug**
This was fixed in a previous release, but with the overhaul / rewrite seems to be an issue again.  The tooltip in the World Map does not scale with the UI scale and is showing extremely large compared to other tooltips.  If there is a work-around, I'll take that instead of a fix if that'll work.  I tried to find the LUA data for it but I'm not seeing anything I can change in there to correct it.

**Expected Behaviour**
Tooltip to scale with the UI Scale

**Comment by Jaliborc** [comment]
Should be fixed again in new version

**Comment by BornabeWylde** [comment]
Works perfectly, thank you!!
