### ISSUE TITLE
Please release on wowinterface too

### ISSUE THREAD

**Issue by p3lim** [Jaliborc/PetTracker#291]

**Comment by gheldean** [comment]
Or alternatively if you're open to wowinterface, it can be updated here with release/version information to be retrievable by WoWup or via Wago/Wowuphub, 

Details on the WoWUp discord if interested :) https://discord.gg/rk4F5aD

**Comment by Barleduq** [comment]
Yes please!

**Comment by Barleduq** [comment]
Also, you can just release it here, also. The addon manager I use, CurseBreaker, needs it to be in the format referenced here: https://github.com/AcidWeb/CurseBreaker/issues/336  which I've been told is a commonly used format to push to Curse (tho I may have misunderstood things completely).

**Comment by Poisonenvy2** [comment]
It's not going to happen.  Author doesn't plan to support any download other than from Curse - see previous closed issues with similar requests.
