### ISSUE TITLE
CustomTutorials bug

### ISSUE THREAD

**Issue by Roneasaurus** [Jaliborc/PetTracker#300]
**Running Software (issues missing this information will be deleted):**
 - Addon version:    10.0-10.0.0.
 - Server patch: [Build 10.0.0.46455]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.  x

**Describe the bug**
the pet tracker frame just sits in the middle of the screen. does nothing, cant be moved, cant be shut.

**To Reproduce**
Steps to reproduce the behaviour:
1. log into game.
2. See error below as soon as you log into game

**Error Logs**

10x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:115: attempt to perform arithmetic on field 'i' (a nil value)
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:115: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:114>

Locals:
(*temporary) = <function> defined @Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
(*temporary) = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to perform arithmetic on field 'i' (a nil value)"
UpdateFrame = <function> defined @Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
frame = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
}
direction = 1

**Additional context**

**Comment by jdmaddison** [comment]
Also getting related CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)

**Comment by stendardo** [comment]
Same here

**Comment by halloaloe** [comment]
I'm having something similar, but from little I understand, it's saying that PetTracker and AlltheThings aren't playing well together, I think? :

26x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:665: in function `TimeManager_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1466: in function <Interface/FrameXML/UIParent.lua:1350>

**Comment by jdmaddison** [comment]
The error on line 55 of CustomTutorials-2.1.lua has been fixed with #313 .
