### ISSUE TITLE
Tutorial window bug

### ISSUE THREAD

**Issue by Duranna144** [Jaliborc/PetTracker#307]
**Running Software (issues missing this information will be deleted):**
 - Addon version:10.0-10.0.0
 - Server patch: 10.0.0

 **Have you read the changelog? Yes

**Describe the bug**
Tutorial frame pops up every time I log in, I am unable to go through it and get the error listed below.

**To Reproduce**
Steps to reproduce the behaviour:
Log in. That is all that I do and this occurs.

**Expected behaviour**
I expect to be able to go through the tutorial and mark it as completed so it does not continue to pop up.

**Error Logs**
5x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:115: attempt to perform arithmetic on field 'i' (a nil value)
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:115: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:114>

Locals:
(*temporary) = <function> defined @Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
(*temporary) = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to perform arithmetic on field 'i' (a nil value)"
UpdateFrame = <function> defined @Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
frame = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
}
direction = 1

**Additional context**
Only other addon enabled was bugsack/buggrabber to get the bugs.

**Comment by Konungrr** [comment]
Same for me.

**Comment by terrybader** [comment]
Got the same.

Commented out line 55 of gossip.lua to get around the problem.
`
frame.TitleText:SetText(data.title or frame.data.title)
`
to 
`
-- frame.TitleText:SetText(data.title or frame.data.title)
`

Since I just went around it, I believe TitleText should just be text but did not reset everything and try it.

**Comment by Duranna144** [comment]
That does seem to have worked!

**Comment by ryankhart** [comment]
> Got the same.
> 
> Commented out line 55 of PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua to get around the problem. `frame.TitleText:SetText(data.title or frame.data.title)` to `-- frame.TitleText:SetText(data.title or frame.data.title)`
> 
> Since I just went around it, I believe TitleText should just be text but did not reset everything and try it.

This worked for me too! Thanks!

**Comment by RuffianCM** [comment]
Hi, is this going to be fixed in the download from CurseForge? I saw this awhile ago and figured it would be corrected soon in an updated version, but the tutorial window keeps popping up every time I log into any WoW character. I really like this addon, but the window popping up every time I switch characters is making me crazy! Thanks!

**Comment by ryankhart** [comment]
> Hi, is this going to be fixed in the download from CurseForge? I saw this awhile ago and figured it would be corrected soon in an updated version, but the tutorial window keeps popping up every time I log into any WoW character. I really like this addon, but the window popping up every time I switch characters is making me crazy! Thanks!

I can't answer for when an official update will fix this, but you may be surprised how simple it is to work-around the issue with the fix described above. The code doesn't need to be compiled, so all it takes it just adding three characters to the beginning of one line "-- " and hit save.

You can use any editor that shows line numbers. If you care about it being lightweight and fast to launch, I recommend [Notepad++](https://notepad-plus-plus.org/). If you want versatility and one editor to rule them all at the expense of launch time and memory usage, I recommend [VS Code](https://code.visualstudio.com/).

**Comment by Elnora** [comment]
I also have this issue.
