### ISSUE TITLE
Pet Tracker not working with UI

### ISSUE THREAD

**Issue by Elaeana** [Jaliborc/PetTracker#31]
I use ElvUI and Pet Tracker doesn't seem to like working with the Main Map in showing where specific pets are in a zone. I have to disable my UI, search for the pet, then enable it in order to find the spots of a pet like the Crimsonwing Moth in talador. I've attached a photo of what my map looks like with the UI on so you can get a better understanding

![2018-04-22](https://user-images.githubusercontent.com/38619182/39095500-5fc09c5e-45f6-11e8-94f9-6a23531570f9.png)

Here is one with my UI off:

![2018-04-20 1](https://user-images.githubusercontent.com/38619182/39095504-7e273acc-45f6-11e8-9ec5-2dde42a0a731.png)

**Comment by gauntlett** [comment]
I'm having the same issue.

**Comment by skupfer** [comment]
Can confirm, with ElvUI disabled, everything is working. With ElvUI enabled, I cannot click on the magnifying class (but icons stay active if enabled without ElvUI enabled).

**Comment by gauntlett** [comment]
After looking through the ElvUI forums I came across some posts where people where having mini-map issues, which might also apply to the main map. Look at this post https://www.tukui.org/forum/viewtopic.php?f=5&t=2317 and find #12 on the second page. (The entry number is located in the top right of each post). Perhaps that build will resolve the matter for you?

**Comment by skupfer** [comment]
Can confirm, fixes the dropdown for the Mini- and Worldmap!

**Comment by Jaliborc** [comment]
Sorry, but this is nothing I can help with.
