### ISSUE TITLE
attempt to index field 'TitleText' (a nil value) on login

### ISSUE THREAD

**Issue by jdmaddison** [Jaliborc/PetTracker#313]
**Running Software (issues missing this information will be deleted):**
 - 10.0.0 (11/1/2022)
 - Server patch: Build 10.0.2 

 **Have you read the changelog? (please don't waste our time)**
Have read changelog.

**Describe the bug**
LUA error on login

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to character
2. See error

**Expected behaviour**
Expected no LUA errors on Login

**Error Logs**
Message: ...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
Time: Sun Nov 20 16:30:43 2022
Count: 1
Stack: ...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
...
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by GurliGebis** [comment]
Can you try and see if the changes from here fixes the issue?

https://github.com/Jaliborc/CustomTutorials-2.1/pull/8

**Comment by IvanDoomer** [comment]
> Can you try and see if the changes from here fixes the issue?
> 
> [Jaliborc/CustomTutorials-2.1#8](https://github.com/Jaliborc/CustomTutorials-2.1/pull/8)

Worked fine forme! o/ Thanks!

**Comment by jdmaddison** [comment]
Tested and Looks good! I have left a comment on the change in GitHub (although I am a GitHub novice).
