### ISSUE TITLE
CustomTutorial Lib Error

### ISSUE THREAD

**Issue by RAtwood90** [Jaliborc/PetTracker#315]
```
1x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:27: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:23>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:62: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@WQAchievements/WQAchievements.lua"]:463: in function <WQAchievements/WQAchievements.lua:391>
...
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:27: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:23>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:62: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1482: in function <FrameXML/UIParent.lua:1362>
```

Getting this Error Today by the todo List to figuring out which Addon is working for DF and which not.

**Comment by Rycia** [comment]
I also have this issue. Please push the fix!

```
246x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1482: in function <FrameXML/UIParent.lua:1362>
```

**Comment by Roneasaurus** [comment]
i also  have been getting this 


5x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@BagBrother/Libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/Libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@BagBrother/Libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/Libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@BagBrother/Libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/Libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@BagBrother/Libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/Libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>

**Comment by Roneasaurus** [comment]
also this one 



16x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:115: attempt to perform arithmetic on field 'i' (a nil value)
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:115: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:114>

Locals:
(*temporary) = <function> defined @PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
(*temporary) = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to perform arithmetic on field 'i' (a nil value)"
UpdateFrame = <function> defined @PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36
frame = CustomTutorials1 {
 0 = <userdata>
 images = <table> {
 }
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:91
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 Inset = CustomTutorials1Inset {
 }
 SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:79
 next = Button {
 }
 text = FontString {
 }
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
 prev = Button {
 }
 shine = Frame {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 SetBorder = <function> defined @SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 flash = AnimationGroup {
 }
 SetPortraitToBag = <function> defined @SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @SharedXML/PortraitFrame.lua:71
 Bg = CustomTutorials1Bg {
 }
 GetPortrait = <function> defined @SharedXML/PortraitFrame.lua:58
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:95
 CloseButton = CustomTutorials1CloseButton {
 }
 unlocked = 4
 data = <table> {
 }
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
}
direction = 1

**Comment by Rycia** [comment]
Getting the same error. Mildly annoying.
```
1x ...ker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@PetTracker/libs/CustomTutorials-2.1-11/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@PetTracker/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <PetTracker/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@PetTracker/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <PetTracker/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1482: in function <FrameXML/UIParent.lua:1362>
```

**Comment by GurliGebis** [comment]
Try and see the link I posted above, for how to work around it for now.
