### ISSUE TITLE
Database for Dragonflight?

### ISSUE THREAD

**Issue by Mike160770** [Jaliborc/PetTracker#317]
Great add-on - is there a timeline when the new pets from the Dragon Isles are included?

**Comment by LordVirus187** [comment]
I was wondering if there was an ETA for this feature, its one of my favs.

**Comment by christopherjbaker** [comment]
Thanks so much for adding that! I was looking through the code to figure out how the data is gathered/encoded so I could open a PR for you, but I couldn't figure it out. If you added some info or a basic script, I'm sure the community would be happy to help you manage this part of the project.
