### ISSUE TITLE
Pets not appearing on World Map

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#321]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0, I think. At least that's what Curseforge shows as the version.
 - Server patch: [e.g. Build 8.0.1.27178] 10.0.2.46924

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes, I've read the changelog, at least what's displayed by Curseforge.

**Describe the bug**
Pets do not show up on the World Map. I usually have it set to show "missing" pets but even when set to show all, nothing shows up on the world map. Yes, I have pet tracking on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to World Map
2. Click on magnifying glass and set "missing" or unset it, or set it to one of the other options. No matter what, nothing shows.

**Expected behaviour**
I expect to see all the wild pets marked on the world map if no search is given, I expect all those I'm missing to be shown when "missing" is in the search box.

**Screenshots**
<img width="1728" alt="Screen Shot 2022-12-12 at 10 40 58 AM" src="https://user-images.githubusercontent.com/26287341/207089101-2d2711af-803e-49a0-b7c6-9ee47de37c83.png">

**Error Logs**
No errors.

**Additional context**
No errors appear in Bugsack

**Comment by DudicusMaximus** [comment]
I think this is less of a bug and more that the data simply isn't put into the addon yet, all the other zones seem to be working aside from the Dragon Isles, at least for me.

**Comment by giloup39** [comment]
Same on Dragon Isles but orks well elsewhere.

**Comment by void269** [comment]
How does the data get added?  Is there a way to contribute?
