### ISSUE TITLE
I keep getting an error

### ISSUE THREAD

**Issue by sarallaii** [Jaliborc/PetTracker#322]
Message: ...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
Time: Mon Dec 12 13:54:52 2022
Count: 1
Stack: ...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:55: attempt to index field 'TitleText' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua"]:55: in function <...ker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua:36>
[string "@Interface/AddOns/PetTracker/libs/CustomTutorials-2.1/CustomTutorials-2.1.lua"]:199: in function `TriggerTutorial'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:36: in function `Start'
[string "@Interface/AddOns/PetTracker/addons/config/tutorials.lua"]:28: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/PetTracker/addons/main/main.lua"]:46: in function `?'
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>

**Comment by tyrrminal** [comment]
My response here (https://github.com/Jaliborc/PetTracker/issues/319#issuecomment-1344345706) addresses this
