### ISSUE TITLE
Fix for the tutorial lua errors (DONT DO IT IF YOU NEED THE TUTORIAL)

### ISSUE THREAD

**Issue by Mystream90** [Jaliborc/PetTracker#333]
Hi,
with some tinkering I found a solution for the massive lua errors caused by the tutorial files when reloading/login. You just have to delete some files and comment out some lines. Steps below:

1.  Go to the "\Interface\AddOns\PetTracker\libs" folder and delete the "CustomTutorials-2.1" folder and the "config.xml" file.
2. Go to the "\Interface\AddOns\PetTracker\addons\config" folder and delete "config.xml" and "tutorials.lua" files.
3. Go to the "\Interface\AddOns\PetTracker\addons\main" folder and open the "main.lua" file with programs like notepad.
4. In line 42 add ```--[[```
5. In line 48 add ```--]]```

You are all set up. I already tested it if I get other errors but it seems like the addons works perfectly fine.

**Comment by efui** [comment]
For me it made the addon broken, not functioning, with too many errors.

**Comment by SargonStarblade** [comment]
> For me it made the addon broken, not functioning, with too many errors.

Did you add the quotation marks? I did and it broke it, but then went and removed the quotations and it worked fine.

**Comment by Mystream90** [comment]
> > For me it made the addon broken, not functioning, with too many errors.
> 
> Did you add the quotation marks? I did and it broke it, but then went and removed the quotations and it worked fine.

No, I did not add the quotations.

**Comment by Bendder** [comment]
All I did to get the errors to stop for now is go to "\Interface\AddoOns\PetTracker\libs\CustomTutorials-2.1" folder.  In there edit the "CustomTutorials-2.1.lua" file, and goto line 55:
Old:  `frame.TitleText:SetText(data.title or frame.data.title)`
New: `--frame.TitleText:SetText(data.title or frame.data.title)`

Add the -- before the frame and save the file.. Reload the UI and navigate through all the tutorials (if they pop up).

**Comment by cobase2010** [comment]
> Hi, with some tinkering I found a solution for the massive lua errors caused by the tutorial files when reloading/login. You just have to delete some files and comment out some lines. Steps below:
> 
> 1. Go to the "\Interface\AddOns\PetTracker\libs" folder and delete the "CustomTutorials-2.1" folder and the "config.xml" file.
> 2. Go to the "\Interface\AddOns\PetTracker\addons\config" folder and delete "config.xml" and "tutorials.lua" files.
> 3. Go to the "\Interface\AddOns\PetTracker\addons\main" folder and open the "main.lua" file with programs like notepad.
> 4. In line 42 add `--[[`
> 5. In line 48 add `--]]`
> 
> You are all set up. I already tested it if I get other errors but it seems like the addons works perfectly fine.

I was able to get rid of the error by simply commenting out line 55 of CustomTutorials-2.1.lua file.

**Comment by cobase2010** [comment]
Basically change line 55 of the CustomTutorials-2.1.lua to
-- frame.TitleText:SetText(data.title or frame.data.title)

**Comment by MilaPi** [comment]
Thanks. It helps with lua errors. If only missing pets tracking worked on the map.
