### ISSUE TITLE
Feature Request: hand over development to someone active

### ISSUE THREAD

**Issue by Rezy942** [Jaliborc/PetTracker#336]
Addon hasnt been updated for a long time now. Bugs that have been present for years are still present.
Such a great addon doesnt deserve to get abandoned.
Addon itself works but the amount of bugs is horrendous.
Will pop back in time to time to see but for now I had to delete the addon. 
I hope someone can take over the project entirely.

**Comment by linda535** [comment]
I totally agree. PetTracker was so useful and saved a huge amount of time looking for pets we didn't already have. It's useless now because of the endless bugs and errors.

**Comment by Rezy942** [comment]
You should reopen this as these kind of requests are the only ones being looked after.

**Comment by linda535** [comment]
Pet Tracker is working very well now. My only (almost nonexistent) complaint is that when I want to only see pet icons for those pets I don't already have, I need to click on another option before clicking on Missing, then it works. Thanks for all your hard work.

**Comment by Rezy942** [comment]
It works but is coded very roughly. There are lines spilling over and icons in front of other menus.
It also doesnt play well with a lot of other addons including Kaliels tracker.
All requests are being ignored (even a simple no would be more helpful).
People are wasting their time for someone who doesnt give 2 ****.
