### ISSUE TITLE
Doesn't work for BFA pre-patch

### ISSUE THREAD

**Issue by ChadCloman** [Jaliborc/PetTracker#35]
PetTracker is marked out of date for today's 8.0 pre-patch, and it has lots lua errors when I force it to load.

I hadn't realized how much I depend on this addon. It's become a significant part of my game.

Please take pity and release a working version!

**Comment by Revenwyn** [comment]
Yes, when I've tried to use it, it made it so that swapping pets in the battle doesn't work. When I disabled it, I was able to swap pets again. But it is much harder for me to find pets that are upgrades.

**Comment by croana** [comment]
I've left some errors in the comments section of the addon on curse.
