### ISSUE TITLE
Why the license change

### ISSUE THREAD

**Issue by GurliGebis** [Jaliborc/PetTracker#360]
Why has the license been changed from GPL-3 to a non-free license (All Rights Reserved) ?

**Comment by Rezy942** [comment]
Its unfortunately considering the addon is 99% abandoned, with updated sprinkled time to time to address any massive issues that would cause people to stop donating. I'm all for life outside WoW, I welcome it. But damn, at least leave a comment or something for your community.

**Comment by GurliGebis** [comment]
Yeah, I know - I have created a private fork, with more updated data and several bug fixes.
However, due to @Jaliborc not wanting to fix them, and not wanting people to work on his "open source" addons, I cannot provide it to anyone. I'm sorry

**Comment by GurliGebis** [comment]
Well, to all the people interested, I have made my own addon (with no code from this addon at all - completely implemented from scratch - though inspired by this addon), that has most of the features that PetTracker has, and is real open source GPL-3 licensed.
It is called `Battle Pet Completionist` - You can find it on curseforge.

I wish I didn't have to go this far, but since PetTracker has been "GPL-3, but with all your freedoms removed", I think it is only fair to have another addon, that is actually open and free software.

**Comment by Rezy942** [comment]
> Well, to all the people interested, I have made my own addon (with no code from this addon at all - completely implemented from scratch - though inspired by this addon), that has most of the features that PetTracker has, and is real open source GPL-3 licensed. It is called `Battle Pet Completionist` - You can find it on curseforge.
> 
> I wish I didn't have to go this far, but since PetTracker has been "GPL-3, but with all your freedoms removed", I think it is only fair to have another addon, that is actually open and free software.

Thank you SO much. Going to download right away and spread the news as much as I can. I hope all PetTracker users switch over and provide support to you via donations etc.

**Comment by GurliGebis** [comment]
@Rezy942 I'm don't have any kind of donations set up, but do spread the word. 🙂

**Comment by GurliGebis** [comment]
@Rezy942 I think linking directly from here is a bit aggressive 🙂
But yeah, new addons take quiet a while to be searchable in the app.
