### ISSUE TITLE
Error on WORLD_MAP_UPDATE in Pre BFA Update

### ISSUE THREAD

**Issue by Lagicrus** [Jaliborc/PetTracker#37]
Date: 2018-07-18 20:07:15
ID: 13
Error occured in: Global
Count: 1
Message: ..\AddOns\PetTracker\PetTracker.lua line 58:
   Attempt to register unknown event "WORLD_MAP_UPDATE"
Debug:
   [C]: RegisterEvent()
   PetTracker\PetTracker.lua:58: ?()
   PetTracker\PetTracker.lua:21:
      PetTracker\PetTracker.lua:21
Locals:
(*temporary) = PetTrackerListener {
 0 = <userdata>
}
(*temporary) = "WORLD_MAP_UPDATE"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  WowheadLooter, v80000
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  Configator, v5.1.DEV.431(/embedded)
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  FishingBuddy, v1.9.1
  Gatherer, v7.3.1
  GatherMate2, v1.42
  InFlightLoad, v8.0.001
  Omen, v3.2.0
  PaidTime, v0.1
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerConfig, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  SlideBar, v7.3.1 (<%codename%>)
  WowLua, vv70300-1.0.1
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=350)

**Comment by funjoker** [comment]
WORLD_MAP_UPDATE  doesn't exist anymore

**Comment by Lagicrus** [comment]
explains the issue then lol, I don't keep a track of the API I was just reporting the issue. Thanks
