### ISSUE TITLE
C_Everywhere is not embedded

### ISSUE THREAD

**Issue by filliph** [Jaliborc/PetTracker#377]
**Which software were you running?**
 - Addon version name: 10.2.2
 - Client used: Retail

**Have you read the changelog?**
Yes

**Please describe the bug.**
Logging in to the game triggers a BugSack error, and the quest list integration does not function.

**Please describe how to reproduce it.**
1. Login
2. See error

**Any Screenshots?**
N/A

**Error Logs are Important!**
```
1x ...ddOns/PetTracker/addons/main/features/objectives.lua:6: Cannot find a library instance of "C_Everywhere".
[string "=[C]"]: in function `error'
[string "@AddonFactory/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@PetTracker/addons/main/features/objectives.lua"]:6: in main chunk
```

**Comment by KingDeVeteran** [comment]
Same-ish error for me:

1x ...ddOns/PetTracker/addons/main/features/objectives.lua:6: Cannot find a library instance of "C_Everywhere".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@PetTracker/addons/main/features/objectives.lua"]:6: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "C_Everywhere"."

**Comment by filliph** [comment]
Fixed in the latest update, thanks 👍
