### ISSUE TITLE
GetMapContinents error in Pre BFA

### ISSUE THREAD

**Issue by Lagicrus** [Jaliborc/PetTracker#39]
Date: 2018-07-18 20:07:09
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\PetTracker\Core\Static.lua line 79:
   attempt to call global 'GetMapContinents' (a nil value)
Debug:
   PetTracker\Core\Static.lua:79: in main chunk
Locals:
_ = "PetTracker"
Addon = <table> {
 NewClass = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:27
 Stats = <table> {
 }
 QualityScale = <table> {
 }
 MaxQuality = 4
 TamerOrder = <table> {
 }
 ForAllModules = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:37
 MaxLevel = 25
 BreedStats = <table> {
 }
 TamerLandmarks = <table> {
 }
 Species = <table> {
 }
 Tamers = <table> {
 }
 Stables = <table> {
 }
 BreedIcons = <table> {
 }
 BreedNames = <table> {
 }
 ContinentByZone = <table> {
 }
 SourceIcons = <table> {
 }
 WORLD_MAP_UPDATE = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:62
 NewModule = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:31
 Locals = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:48
 Breeds = <table> {
 }
 PET_JOURNAL_LIST_UPDATE = <function> defined @Interface\AddOns\PetTracker\PetTracker.lua:75
}
Missing = <table> {
 GetRGB = <function> defined @Interface\SharedXML\Util.lua:615
 OnLoad = <function> defined @Interface\SharedXML\Util.lua:604
 b = 0.1
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Util.lua:646
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Util.lua:650
 GenerateHexColor = <function> defined @Interface\SharedXML\Util.lua:642
 GetRGBA = <function> defined @Interface\SharedXML\Util.lua:623
 IsEqualTo = <function> defined @Interface\SharedXML\Util.lua:608
 g = 0.1
 r = 1
 SetRGBA = <function> defined @Interface\SharedXML\Util.lua:631
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Util.lua:619
 SetRGB = <function> defined @Interface\SharedXML\Util.lua:638
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Util.lua:627
}
L = <table> {
 UnlockActions = "Unlock Enemy Actions"
 Tutorial = <table> {
 }
 TellMore = "Tell me more about yourself."
 Species = "Species"
 Maximized = "Maximized"
 JournalTutorial = <table> {
 }
 Ninja = "Ninja"
 AddWaypoint = "Add Waypoint"
 AvailableBreeds = "
Available Breeds:"
 Battles = "Battles"
 Breed = "Breed"
 Victory = "Victory"
 Source11 = "Discovery"
 AlertUpgrades = "Alert for Upgrades"
 Source10 = "In-Game Shop"
 EnemyTeam = "Enemy Team"
 Source9 = "Trading Card Game"
 Source8 = "Promotion"
 Source4 = "Profession"
 Source7 = "World Event"
 Source6 = "Achievement"
 ShowJournal = "Show in Journal"
 UpgradeAlert = "Wild upgrades have appeared!"
 UnlockActionsTip = "If enabled, the enemy actions bar can be dragged to anywhere on the screen."
 Defeat = "Defeat"
 Source1 = "Drop"
 StableTip = "Come here to heal your
pets for a small fee."
 Source2 = "Quest"
 CapturedPets = "Show Captured"
 Rivals = "Rivals"
 NoHistory = "PetTracker has never seen you
fight this adversary"
 AlertUpgradesTip = "If disabled, the wild upgrades alert box will not be shown in combat, but upgrades will still be marked with a symbol ()."
 ShowPets = "Show Battle Pets"
 ZoneTracker = "Zone Tracker"
 FAQ = <table> {
 }
 TotalTamers = "Total Rivals"
 CommonSearches = "Common Searches"
 Source5 = "Pet Battle"
 BreedExplanation = "Determines how stats gained at each level are distributed."
 LoadTeam = "Load Team"
 PromptForfeit = "Prompt for Forfeit"
 FilterPets = "Filter Pets"
 Source3 = "Vendor"
 TrackPets = "Track Pets"
 AskForfeit = "No upgrades are available. Quit battle?"
 ShowStables = "Show Stables"
 PromptForfeitTip = "If enabled, you will be prompted to forfeit a battle when no upgrades are available."
 NoneCollected = "None Collected"
}
(*temporary) = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = "#"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMapContinents' (a nil value)"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  WowheadLooter, v80000
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  Configator, v5.1.DEV.431(/embedded)
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  FishingBuddy, v1.9.1
  Gatherer, v7.3.1
  GatherMate2, v1.42
  InFlightLoad, v8.0.001
  Omen, v3.2.0
  PaidTime, v0.1
  PetTracker, v7.3.0
  SlideBar, v7.3.1 (<%codename%>)
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=2c8)

**Comment by moogloogle** [comment]
What are the full ramifications of this error? I'm trying to figure out if I have a different issue or not.
