### ISSUE TITLE
looking for an update for BFA pre 8.0.1 pls

### ISSUE THREAD

**Issue by rhainstorm** [Jaliborc/PetTracker#40]
as of pre-release pet tracker is very broke. 
can we pls get an update for this great addon or an eta on one. 

ty for the work you do this addon. is one of my favorites. 

any info would be appreciated so we know you plan to and are still working on it and its not abandoned

**Comment by BigFire321** [comment]
To be more specific, if the addon is loaded, the pet battle cannot switch pet.  I don't know what else is broken, but that's a big one.
