### ISSUE TITLE
Ability to only show pets not yet collected

### ISSUE THREAD

**Issue by Flamenica** [Jaliborc/PetTracker#50]
I am sure there used to be an option to filter collected/not collected pets on the world map - currently the world map is a tad cluttered !

**Comment by bousteur** [comment]
I have to agree, current map is overcrowded by collected pets.

**Comment by pt87** [comment]
I found this add on the day before the patch. When viewing the world map it only showed pets I had not collected, perfect. If we can back to that, it would be great, unless I am missing something and there is a way to configure pet tracker in game.

**Comment by Flamenica** [comment]
This is NOT an invalid issue.  There has been no fix or work around given.
