### ISSUE TITLE
LUA error after login

### ISSUE THREAD

**Issue by KJanos1396** [Jaliborc/PetTracker#51]
Message: Error loading Interface\AddOns\PetTracker\Libs\Sushi-3.0\Classes\GlowBox.lua
Time: Sat Jul 28 10:57:41 2018
Count: 4
Stack: Error loading Interface\AddOns\PetTracker\Libs\Sushi-3.0\Classes\GlowBox.lua

Locals: <none>

Message: Couldn't open Interface\AddOns\PetTracker\Core\Tests\Include.xml
Time: Sat Jul 28 10:57:41 2018
Count: 2
Stack: **Couldn't open Interface\AddOns\PetTracker\Core\Tests\Include.xml**

Locals: <none>

Message: Error loading Interface\AddOns\PetTracker\Core\Compare.lua
Time: Sat Jul 28 10:57:41 2018
Count: 4
Stack: Error loading Interface\AddOns\PetTracker\Core\Compare.lua

Locals: <none>

**Comment by sgkdnay** [comment]
Got the same error as well!
