### ISSUE TITLE
Unable to select 2nd battle pet when 1st one dies

### ISSUE THREAD

**Issue by Sytara** [Jaliborc/PetTracker#56]
**Running Software (please complete the following information):**
- Game patch 8.0.1
- Addon version 8.0.0

**Describe the bug**
If I have PetTracker loaded and I engage in a battle with 3 pets, once the first pet dies, i don't get an option to select between the remaining two pets.  I can only forfeit.  If there's only one pet left with health then it will automatically put that pet in, but if I have two healthy pets, i can't pick between them. If I unload PetTracker then i can don't get the error while competing in a pet battle.

**To Reproduce**
1. Enter a pet battle against any pet found in wild.
2. First pet dies and area that shows pet battle abilities goes blank and doesn't give an option between the two remaining pets
3. Only option is to forfeit battle and turn off PetTracker

**Expected behavior**
When my first battle pet dies, I expect to see the two remaining pets pop up in the pet battle ability area for me to choose which one to battle next.

**Screenshots**

![pettracker screenshot](https://user-images.githubusercontent.com/41883436/43376280-b2da2a3e-936e-11e8-8db9-788d57ff430b.png)

**Comment by SFFCorgi** [comment]
I have experienced the exact same problem, just as you described it; I think I must have commented in discussion, not a ticket.  I first encountered it doing a Tamer battle, not a wild battle, but the same error occurred.

**Comment by Jaliborc** [comment]
PetTracker does not interact with the default ability buttons at all. **This is the work of an enemy stand.**
JK, this is caused by some other addon. I verified, just in case, and PetTracker isn't causing it.
