### ISSUE TITLE
PetTracker hides Broken Isles pet-related world quests, even when not obscured

### ISSUE THREAD

**Issue by ChadCloman** [Jaliborc/PetTracker#74]
**Running Software (please complete the following information):**

 - Game patch: whatever the latest version is, as of 8/3/2018
 - Addon version: 8.0.4

**Have you read the changelog? (please don't waste our time)**

Yes

**Describe the bug**

When PetTracker is enabled, pet-related world quests do not appear on the map.

Note that this is different than issue #72, because it happens even when the world quest icon is not obscured.

**To Reproduce**

See [this video](https://youtu.be/exnLCJcs8Jg) for a clear demonstration of the problem and how to reproduce it.

**Expected behavior**

Pet-related world quests appear on the map.

**Screenshots**

I created a short video demonstrating the problem: [https://youtu.be/exnLCJcs8Jg](https://youtu.be/exnLCJcs8Jg)

**Other Information**

This is new behavior in 8.0.4. Before the 8.0.4 release, I could see the pet-related world quests with no problem.

**Comment by Petetsmisc** [comment]
I 100% agree with ChadClomanQ!! The portrait icons are nice but atm, this breaks WQ pet battle tracking!

Not only that, but the icons show up even when that Pet Boss is NOT available! If you're going to be using these portrait icons, than do so when the WQ Boss is actually available at that location.

Right now PetTracker is NOT working properly (the very latest version).

**Comment by ChadCloman** [comment]
Suddenly it's working correctly, without a PetTracker update. Not sure what happened here.

![pettracker](https://user-images.githubusercontent.com/41342202/43672644-6e683ad8-9780-11e8-984b-007f2c7e7479.png)

**Comment by Neodiun** [comment]
Yesterday it worked fine (just like in the picture above), today I havent been able to see any pet battle quests while having PetTracker enabled. =(
So I have to disable the addon to be able to see pet battle quests.
I agree that those icons are very nice, but it would be much more usefull, if those icons were up only when the actual quest is up for that npc =)
I love this addon, but after updating it to 8.0.4 those pet battle quest icons disappeared.

**Comment by gruubar** [comment]
if I rename Features/MapFilter.lua I get a LUA error, but the WQ issue is fixed.
