### ISSUE TITLE
PetTracker 8.0.4 from Twitch Error/Bug

### ISSUE THREAD

**Issue by sgkdnay** [Jaliborc/PetTracker#75]
Logged in, got error:

Bug #1
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\Dropdown.lua`

Bug#2
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\TabGroup.lua`

Bug #3 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\FauxScrollGroup.lua`

Bug #4 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\IconCheck.lua`

Bug #5
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\ExpandCheck.lua`

Bug #6 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\ColorPicker.lua`

Bug #7 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\TextureButton.lua`

Bug #8 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\TabButtons.lua`

Bug #9 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\HelpButton.lua`

Bug #10 
`1x Error loading PetTracker\Libs\Sushi-3.0\Classes\GrayButton.lua`

Bug #11 
`4x Error loading PetTracker\Core\Compare.lua`

**Comment by Daervon** [comment]
In addition to the 11 errors listed above, I am getting the following as well:

Message: Error loading Interface\AddOns\PetTracker\Libs\Sushi-3.0\Classes\TextureDropdown.lua
Time: Fri Aug  3 18:07:03 2018
Count: 4

Message: Error loading Interface\AddOns\PetTracker\Libs\Sushi-3.0\Classes\Slider.lua
Time: Fri Aug  3 18:07:03 2018
Count: 4

This is with only PetTracker loaded, no other addons. I also made certain it was a fresh install, with no older files or variables left over from previous versions.
