### ISSUE TITLE
PetTracker 8.0.4: issues loading Compare.lua and Sushi-3.0

### ISSUE THREAD

**Issue by xaelophorus** [Jaliborc/PetTracker#76]
Every time the interface is loaded or reloaded, a series of errors mostly centered around Sushi 3.0 are caught by BugSack (see below). This is from PetTracker 8.0.4, with no add-ons enabled but PetTracker, BugSack, and BugGrabber.

![pettrackerluaerrors](https://user-images.githubusercontent.com/4138263/43680844-70f9def0-9811-11e8-94d0-82e12f2d98c5.png)

**Comment by Astug** [comment]
Yeah, same issue here.

Message: Error loading Interface\AddOns\PetTracker\Core\Compare.lua
Time: Fri Aug 10 11:35:51 2018
Count: 4
