### ISSUE TITLE
Ability to track missing rares

### ISSUE THREAD

**Issue by schaable** [Jaliborc/PetTracker#79]
**Is your feature request related to a problem? Please describe.**
When I'm hunting battle pets I'm only interested in the ones of rare quality. So every time I start a fight, I have to check every pet with an exclamation mark to see the quality.

**Describe the solution you'd like**
It would be great if you could just add an option to only track rare pets, so if I enter into a battle and see no exclamation marks I can surrender because all pets would be below rare quality.

**Comment by Jaliborc** [comment]
already possible
