### ISSUE TITLE
Resize option for Species/Battle icons

### ISSUE THREAD

**Issue by skupfer** [Jaliborc/PetTracker#80]
**Is your feature request related to a problem? Please describe.**
Especially the Battle icons are way too large and I didn't find an option in the configs (never written lua) out of the box to change the size

**Describe the solution you'd like**
An option to adjust the size for both Species and Battle icons

**Describe alternatives you've considered**
Can't think of an alternative

**Additional context**
These are the lines for Species which would need an option within the config window (thanks to Serpinecoh@curseforge)

```
function Pin:OnCreate()
  self.__super.OnCreate(self)
  self.icon:SetTexCoord(0.79687500, 0.49218750, 0.50390625, 0.65625000)
  self.icon:SetSize(10, 10)

  self:SetScript('OnClick', self.OnClick)
  self:SetSize(10, 10)
end
```

**Comment by Xarxandra** [comment]
I would like to 2nd this idea. The battle trainers' pictures are so big they obscure some of the other things going on near them on the map. Reducing their size to match the size of daily quest icons or pet battle icons (or at least giving us the option to) would be a huge help. Currently if you turn off "Battles" to get rid of that big picture you can no longer see the pet battle dailies that are up. Thank you.

**Comment by series6** [comment]
Save a copy before and after - as if you auto update the addon it will overwrite the changes.

Go to our wow folder and to /AddOns/PetTracker/Components/Maps/RivalPin.lua

Open in notepad go and download Notepad++ 
Open RivalPin.lua

Cntr-F to find Pin:OnCreate() and add in the lines: (before the End command)
  self.icon:SetSize(20, 20)
  self:SetSize(20, 20)
 
 Go to the bottom of the function Pin:Display(rival) and (before the End command)
 add the line:
self.Background:SetSize(20, 20)

or you can delete the map pins altogether.

Go to -
PetTracker\Features\MapCanvas.lua

change it to:

local pin = Addon.RivalPin()
pin:PlaceEncoded(frame, index, spot:match('(%w%w)(%w%w)'))
pin:Display(rival)

perhaps change it to readonly.
