### ISSUE TITLE
A way to resize/hide/change trainer map icons

### ISSUE THREAD

**Issue by alessandrouw** [Jaliborc/PetTracker#96]
**Is your feature request related to a problem? Please describe.**
No, in the past, trainers/elite pets were shown in the map as green or yellow paw icons. Now they're this giant circle, it's very obnoxious.

**Describe the solution you'd like**
A way to change it back to paws, resize or just hide it would be idea.

**Describe alternatives you've considered**
Said before, it's not really something with other alternatives.

**Additional context**
Nothing to add here

**Comment by Lufunpsy** [comment]
The paws are still there, however they are completely obscured by the portraits making a mouseover of the WQ for it impossible. It also contains superfluous information about the Fight Night pet battles when any one of them are active. For Fight Night only the active WQ trainer/pet should be visible.

**Comment by alessandrouw** [comment]
Yes, and the portrait is added by the addon, without any option to disable it. It was not the case in Legion

**Comment by AlphaX79** [comment]
I'd love a way to disable/resize pins without loosing sight on pet battles world quests as it happens when you disable "battles" in map options

**Comment by Jaliborc** [comment]
Added requested option
