### ISSUE TITLE
World Map Tracking Enhanced doesn't work with the search box

### ISSUE THREAD

**Issue by Hawkling** [Jaliborc/PetTracker#97]
without the tracking addon![wowscrnshot_092018_010745](https://user-images.githubusercontent.com/43425057/45786752-3bc72280-bc72-11e8-9ce6-c89c76865b5f.jpg)
with the tracking addon
![wowscrnshot_092018_010812](https://user-images.githubusercontent.com/43425057/45786753-3cf84f80-bc72-11e8-86c3-31c1e117ccf9.jpg)

is there any way you can fix it?

**Comment by arithmandar** [comment]
This issue has been resolved.
Details: [here](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced/issues/6).

**Comment by Jaliborc** [comment]
Nice!
